COMMENT ON COLUMN RECEIPT_ITEMS.DEFECT_QUANTITY IS
    '불량 수량';
COMMIT;
-- 더미데이터 START--
INSERT INTO STORES(STORE_ID,
                   STORE_CODE,
                   STORE_NAME,
                   PHONE,
                   ADDRESS,
                   OWNER_USER_ID,
                   CREATED_BY,
                   UPDATED_BY,
                   UPDATED_AT)
           VALUES (00,
                   'S00',
                   '서울역',
                   '010-1111-1111',
                   '서울특별시 용산구 한강대로 405',
                   2,
                   1,
                   1,
                   SYSDATE);

INSERT INTO PURCHASE_REQUESTS(PURCHASE_REQUEST_ID,
                               STORE_ID,
                               STATUS,
                               TOTAL_AMOUNT,
                               REQUEST_MEMO,
                               CREATED_BY,
                               UPDATED_BY,
                               UPDATED_AT)
                       VALUES (0,
                               00,
                               'REQUESTED',
                               55,
                               '발주 더미데이터00',
                               2,
                               1,
                               SYSDATE);

INSERT INTO PURCHASE_REQUESTS(PURCHASE_REQUEST_ID,
                               STORE_ID,
                               STATUS,
                               TOTAL_AMOUNT,
                               REQUEST_MEMO,
                               CREATED_BY,
                               UPDATED_BY,
                               UPDATED_AT)
                       VALUES (1,
                               00,
                               'APPROVED',
                               55,
                               '발주 더미데이터00',
                               2,
                               1,
                               SYSDATE);

INSERT INTO RECEIPTS
     VALUES(999, 00, 00, 'DUMMY_DATA_RECEIPTS00', 2, SYSDATE); 
     
-- 자재 Materials
INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT001', '참깨번', 'BUN',
    500, 1000, NULL, '햄버거용 참깨 번',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);

INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT002', '비프패티', 'PATTY',
    2000, 3500, NULL, '100% 소고기 패티',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);

INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT003', '체다치즈', 'CHEESE',
    300, 700, NULL, '슬라이스 체다치즈',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);

INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT004', '양상추', 'VEGETABLE',
    200, 500, NULL, '신선한 양상추',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);

INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT005', '토마토', 'VEGETABLE',
    250, 600, NULL, '슬라이스 토마토',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);

INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT006', '양파', 'VEGETABLE',
    150, 400, NULL, '슬라이스 양파',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);

INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT007', '피클', 'VEGETABLE',
    100, 300, NULL, '오이 피클',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);

INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT008', '베이컨', 'TOPPING',
    800, 1500, NULL, '훈제 베이컨',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);

INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT009', '마요네즈', 'SAUCE',
    100, 300, NULL, '고소한 마요네즈',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);

INSERT INTO MATERIALS (
    MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MATERIAL_TYPE,
    COST_PRICE, SELLING_PRICE, IMAGE_FILE_ID, DETAILS,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_MATERIAL.NEXTVAL, 'MAT010', '케첩', 'SAUCE',
    80, 250, NULL, '토마토 케첩',
    'ACTIVE', 1, SYSDATE, NULL, NULL
);
     
-- 더미데이터 END --

---------------------------------------

-- 입고이력 목록 페이지 수 
SELECT COUNT(*)
  FROM RECEIPTS
 WHERE STORE_ID = ?;
 
-- 입고예정 목록 페이지 수
SELECT COUNT(*)
  FROM PURCHASE_REQUESTS
 WHERE STATUS = 'APPROVED' || 'PARTIALLY_APPROVED' -- APPROVED : 승인
   AND STORE_ID = ?;
   
-- 입고예정 목록 조회
-- 발주 번호, 상태, 품목요약, 총액, 요청일
SELECT PR.PURCHASE_REQUEST_ID,
       PR.STATUS,
       --품목요약,
       PRITEM.SUBTOTAL_AMOUNT,
       PR.CREATED_AT,
       PR.UPDATED_AT
  FROM PURCHASE_REQUESTS PR
  JOIN PURCHASE_REQUEST_ITEMS PRITEM
    ON PR.PURCHASE_REQUEST_ID = PRITEM.PURCHASE_REQUEST_ID;
       
-- 발주 요청 목록 조회 (자재 정보 나와야 함)
-- 품목명, 원가, 재고, 구매가격, 상태
SELECT MATERIAL_NAME,
       COST_PRICE,
       CURRENT_QUANTITY,
       STATUS
  FROM MATERIALS M
  JOIN STORE_INVENTORIES I
    ON M.MATERIAL_ID = I.MATERIAL_ID
 WHERE I.STORE_ID = ?; 

-- 테스트
SELECT *
FROM PURCHASE_ORDERS P
LEFT JOIN PURCHASE_ORDER_ITEMS I
    ON P.PURCHASE_ORDER_ID = I.PURCHASE_ORDER_ID
LEFT JOIN MATERIALS M
    ON I.MATERIAL_ID = M.MATERIAL_ID
LEFT JOIN STORE_INVENTORIES INV
    ON INV.MATERIAL_ID = M.MATERIAL_ID
   AND INV.STORE_ID = P.STORE_ID
WHERE P.PURCHASE_ORDER_ID = 25;

SELECT *
FROM PURCHASE_ORDERS P
LEFT JOIN PURCHASE_ORDER_ITEMS I
    ON P.PURCHASE_ORDER_ID = I.PURCHASE_ORDER_ID
LEFT JOIN MATERIALS M
    ON I.MATERIAL_ID = M.MATERIAL_ID
LEFT JOIN STORE_INVENTORIES INV
    ON INV.MATERIAL_ID = M.MATERIAL_ID
   AND INV.STORE_ID = P.STORE_ID
WHERE P.PURCHASE_ORDER_ID = 26;