-- =========================================================
-- 00_drop.sql
-- 역할:
--   - 기존 테이블 및 시퀀스 제거
-- 실행 시점:
--   - 데모 데이터 재구성 전에 가장 먼저 실행
-- 주의:
--   - 없는 객체를 DROP 하면 Oracle 에러가 발생할 수 있음
-- =========================================================

DROP TABLE INQUIRY_FILES CASCADE CONSTRAINTS;
DROP TABLE INQUIRIES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INQ_FILE;
DROP SEQUENCE SEQ_INQ;

DROP TABLE NOTICE_FILES CASCADE CONSTRAINTS;
DROP TABLE NOTICES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_NOTICE_FILE;
DROP SEQUENCE SEQ_NOTICE;

DROP TABLE INVENTORY_TRANSACTION_ITEMS CASCADE CONSTRAINTS;
DROP TABLE INVENTORY_TRANSACTIONS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INV_TX_ITEM;
DROP SEQUENCE SEQ_INV_TX;

DROP TABLE STORE_CLOSING_ITEMS CASCADE CONSTRAINTS;
DROP TABLE STORE_CLOSINGS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE_CLS_ITEM;
DROP SEQUENCE SEQ_STORE_CLS;

DROP TABLE RECEIPT_ITEMS CASCADE CONSTRAINTS;
DROP TABLE RECEIPTS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_RECEIPT_ITEM;
DROP SEQUENCE SEQ_RECEIPT;

DROP TABLE PURCHASE_ORDER_HISTORIES CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_ORDER_ITEMS CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_ORDERS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PUR_REQ_HIST;
DROP SEQUENCE SEQ_PUR_REQ_ITEM;
DROP SEQUENCE SEQ_PUR_REQ;

DROP TABLE STORE_INVENTORIES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE_INV;

DROP TABLE MATERIAL_FILES CASCADE CONSTRAINTS;
DROP TABLE MATERIALS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MAT_FILE;
DROP SEQUENCE SEQ_MATERIAL;

DROP TABLE STORES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE;

DROP TABLE USERS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_USER;
