-- =========================================================
-- 01_schema.sql
-- 역할:
--   - 테이블 생성
--   - 시퀀스 생성
--   - 테이블/컬럼 COMMENT 정의
-- 포함 범위:
--   - 기준 데이터, 발주, 입고, 마감, 재고 변동, 공지, 문의 스키마
-- =========================================================

CREATE TABLE USERS (
    USER_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(30),
    EMAIL VARCHAR2(100),
    ROLE VARCHAR2(20) DEFAULT 'OWNER' NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_NO),
    CONSTRAINT UK_USERS_USER_ID UNIQUE (USER_ID),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('OWNER', 'ADMIN')),
    CONSTRAINT CK_USERS_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

CREATE SEQUENCE SEQ_USER START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE USERS IS '사용자';
COMMENT ON COLUMN USERS.USER_NO IS '사용자 번호';
COMMENT ON COLUMN USERS.USER_ID IS '아이디';
COMMENT ON COLUMN USERS.PASSWORD IS '비밀번호';
COMMENT ON COLUMN USERS.USER_NAME IS '이름';
COMMENT ON COLUMN USERS.PHONE IS '연락처';
COMMENT ON COLUMN USERS.EMAIL IS '이메일';
COMMENT ON COLUMN USERS.ROLE IS '역할';
COMMENT ON COLUMN USERS.STATUS IS '상태';
COMMENT ON COLUMN USERS.CREATED_AT IS '생성일시';

CREATE TABLE STORES (
    STORE_ID NUMBER NOT NULL,
    STORE_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    OWNER_USER_NO NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STORES PRIMARY KEY (STORE_ID),
    CONSTRAINT UK_STORES_OWNER UNIQUE (OWNER_USER_NO),
    CONSTRAINT CK_STORES_STATUS CHECK (STATUS IN ('OPEN', 'PAUSED', 'CLOSED')),
    CONSTRAINT FK_STORES_OWNER FOREIGN KEY (OWNER_USER_NO)
        REFERENCES USERS (USER_NO)
);

CREATE SEQUENCE SEQ_STORE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORES IS '점포';
COMMENT ON COLUMN STORES.STORE_ID IS '점포 ID';
COMMENT ON COLUMN STORES.STORE_NAME IS '점포명';
COMMENT ON COLUMN STORES.PHONE IS '점포 전화번호';
COMMENT ON COLUMN STORES.ADDRESS IS '점포 주소';
COMMENT ON COLUMN STORES.STATUS IS '상태';
COMMENT ON COLUMN STORES.CREATED_AT IS '생성일시';
COMMENT ON COLUMN STORES.OWNER_USER_NO IS '점주 사용자 ID';

CREATE TABLE MATERIALS (
    MATERIAL_ID NUMBER NOT NULL,
    MATERIAL_NAME VARCHAR2(100) NOT NULL,
    MATERIAL_TYPE VARCHAR2(50) NOT NULL,
    SUPPLY_PRICE NUMBER(12) NOT NULL,
    DETAILS VARCHAR2(3000),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    CONSTRAINT PK_MATERIALS PRIMARY KEY (MATERIAL_ID),
    CONSTRAINT CK_MATERIALS_TYPE CHECK (MATERIAL_TYPE IN ('AF', 'RF', 'FF', 'PK', 'KW', 'ET')),
    CONSTRAINT CK_MATERIALS_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

CREATE SEQUENCE SEQ_MATERIAL START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE MATERIALS IS '자재';
COMMENT ON COLUMN MATERIALS.MATERIAL_ID IS '자재 ID';
COMMENT ON COLUMN MATERIALS.MATERIAL_NAME IS '자재명';
COMMENT ON COLUMN MATERIALS.MATERIAL_TYPE IS '자재 유형';
COMMENT ON COLUMN MATERIALS.SUPPLY_PRICE IS '공급가';
COMMENT ON COLUMN MATERIALS.STATUS IS '상태';
COMMENT ON COLUMN MATERIALS.CREATED_AT IS '생성일시';
COMMENT ON COLUMN MATERIALS.UPDATED_AT IS '수정일시';

CREATE TABLE MATERIAL_FILES (
    MATERIAL_FILE_ID NUMBER NOT NULL,
    ORIGINAL_NAME VARCHAR2(255) NOT NULL,
    STORED_NAME VARCHAR2(255) NOT NULL,
    STORAGE_PATH VARCHAR2(500) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    DELETED_AT DATE,
    MATERIAL_ID NUMBER NOT NULL,
    CONSTRAINT PK_MATERIAL_FILES PRIMARY KEY (MATERIAL_FILE_ID),
    CONSTRAINT FK_MATERIAL_FILES_MAT FOREIGN KEY (MATERIAL_ID)
        REFERENCES MATERIALS (MATERIAL_ID)
);

CREATE SEQUENCE SEQ_MAT_FILE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE MATERIAL_FILES IS '자재 파일';
COMMENT ON COLUMN MATERIAL_FILES.MATERIAL_FILE_ID IS '자재 파일 ID';
COMMENT ON COLUMN MATERIAL_FILES.ORIGINAL_NAME IS '원본 파일명';
COMMENT ON COLUMN MATERIAL_FILES.STORED_NAME IS '저장 파일명';
COMMENT ON COLUMN MATERIAL_FILES.STORAGE_PATH IS '저장 경로';
COMMENT ON COLUMN MATERIAL_FILES.CREATED_AT IS '생성일시';
COMMENT ON COLUMN MATERIAL_FILES.DELETED_AT IS '삭제일시';
COMMENT ON COLUMN MATERIAL_FILES.MATERIAL_ID IS '자재 ID';

CREATE TABLE STORE_INVENTORIES (
    STORE_INVENTORY_ID NUMBER NOT NULL,
    CURRENT_QUANTITY NUMBER(10) DEFAULT 0 NOT NULL,
    SAFETY_QUANTITY NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    STORE_ID NUMBER NOT NULL,
    MATERIAL_ID NUMBER NOT NULL,
    CONSTRAINT PK_STORE_INV PRIMARY KEY (STORE_INVENTORY_ID),
    CONSTRAINT UK_STORE_INV_MAT UNIQUE (STORE_ID, MATERIAL_ID),
    CONSTRAINT FK_STORE_INV_STORE FOREIGN KEY (STORE_ID)
        REFERENCES STORES (STORE_ID),
    CONSTRAINT FK_STORE_INV_MAT FOREIGN KEY (MATERIAL_ID)
        REFERENCES MATERIALS (MATERIAL_ID)
);

CREATE SEQUENCE SEQ_STORE_INV START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORE_INVENTORIES IS '점포 재고';
COMMENT ON COLUMN STORE_INVENTORIES.STORE_INVENTORY_ID IS '점포 재고 ID';
COMMENT ON COLUMN STORE_INVENTORIES.CURRENT_QUANTITY IS '현재 재고 수량';
COMMENT ON COLUMN STORE_INVENTORIES.SAFETY_QUANTITY IS '안전 재고 수량';
COMMENT ON COLUMN STORE_INVENTORIES.CREATED_AT IS '생성일시';
COMMENT ON COLUMN STORE_INVENTORIES.UPDATED_AT IS '수정일시';
COMMENT ON COLUMN STORE_INVENTORIES.STORE_ID IS '점포 ID';
COMMENT ON COLUMN STORE_INVENTORIES.MATERIAL_ID IS '자재 ID';

CREATE TABLE PURCHASE_ORDERS (
    PURCHASE_ORDER_ID NUMBER NOT NULL,
    TOTAL_AMOUNT NUMBER(12) DEFAULT 0 NOT NULL,
    ORDER_MEMO VARCHAR2(1000),
    STATUS VARCHAR2(30) DEFAULT 'REQUESTED' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    STORE_ID NUMBER NOT NULL,
    CONSTRAINT PK_PUR_REQ PRIMARY KEY (PURCHASE_ORDER_ID),
    CONSTRAINT CK_PUR_REQ_STATUS
        CHECK (STATUS IN ('REQUESTED', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', 'CANCELED', 'RECEIVED')),
    CONSTRAINT FK_PUR_REQ_STORE FOREIGN KEY (STORE_ID)
        REFERENCES STORES (STORE_ID)
);

CREATE SEQUENCE SEQ_PUR_REQ START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE PURCHASE_ORDERS IS '발주';
COMMENT ON COLUMN PURCHASE_ORDERS.PURCHASE_ORDER_ID IS '발주 ID';
COMMENT ON COLUMN PURCHASE_ORDERS.TOTAL_AMOUNT IS '총액';
COMMENT ON COLUMN PURCHASE_ORDERS.ORDER_MEMO IS '발주 메모';
COMMENT ON COLUMN PURCHASE_ORDERS.STATUS IS '상태';
COMMENT ON COLUMN PURCHASE_ORDERS.CREATED_AT IS '생성일시';
COMMENT ON COLUMN PURCHASE_ORDERS.UPDATED_AT IS '수정일시';
COMMENT ON COLUMN PURCHASE_ORDERS.STORE_ID IS '점포 ID';

CREATE TABLE PURCHASE_ORDER_ITEMS (
    PURCHASE_ORDER_ITEM_ID NUMBER NOT NULL,
    REQUEST_QUANTITY NUMBER(10) NOT NULL,
    APPROVED_QUANTITY NUMBER(10) DEFAULT 0 NOT NULL,
    REJECT_REASON VARCHAR2(1000),
    MATERIAL_NAME_SNAPSHOT VARCHAR2(100) NOT NULL,
    SUPPLY_PRICE_SNAPSHOT NUMBER(12) NOT NULL,
    MATERIAL_ID NUMBER NOT NULL,
    PURCHASE_ORDER_ID NUMBER NOT NULL,
    CONSTRAINT PK_PUR_REQ_ITEM PRIMARY KEY (PURCHASE_ORDER_ITEM_ID),
    CONSTRAINT UK_PUR_REQ_ITEM_MAT UNIQUE (PURCHASE_ORDER_ID, MATERIAL_ID),
    CONSTRAINT FK_PUR_ITEM_REQ FOREIGN KEY (PURCHASE_ORDER_ID)
        REFERENCES PURCHASE_ORDERS (PURCHASE_ORDER_ID),
    CONSTRAINT FK_PUR_ITEM_MAT FOREIGN KEY (MATERIAL_ID)
        REFERENCES MATERIALS (MATERIAL_ID)
);

CREATE SEQUENCE SEQ_PUR_REQ_ITEM START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE PURCHASE_ORDER_ITEMS IS '발주 상세';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.PURCHASE_ORDER_ITEM_ID IS '발주 상세 ID';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.REQUEST_QUANTITY IS '요청 수량';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.APPROVED_QUANTITY IS '승인 수량';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.REJECT_REASON IS '품목 반려 사유';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.MATERIAL_NAME_SNAPSHOT IS '자재명 스냅샷';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.SUPPLY_PRICE_SNAPSHOT IS '공급가 스냅샷';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.PURCHASE_ORDER_ID IS '발주 ID';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.MATERIAL_ID IS '자재 ID';

CREATE TABLE PURCHASE_ORDER_HISTORIES (
    PURCHASE_ORDER_HISTORY_ID NUMBER NOT NULL,
    TO_STATUS VARCHAR2(30) NOT NULL,
    REASON VARCHAR2(1000),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY NUMBER NOT NULL,
    PURCHASE_ORDER_ID NUMBER NOT NULL,
    CONSTRAINT PK_PUR_REQ_HIST PRIMARY KEY (PURCHASE_ORDER_HISTORY_ID),
    CONSTRAINT FK_PUR_HIST_REQ FOREIGN KEY (PURCHASE_ORDER_ID)
        REFERENCES PURCHASE_ORDERS (PURCHASE_ORDER_ID),
    CONSTRAINT FK_PUR_HIST_USER FOREIGN KEY (CREATED_BY)
        REFERENCES USERS (USER_NO)
);

CREATE SEQUENCE SEQ_PUR_REQ_HIST START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE PURCHASE_ORDER_HISTORIES IS '발주 이력';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.TO_STATUS IS '변경 후 상태';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.REASON IS '상태 변경 사유';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.CREATED_AT IS '생성일시';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.CREATED_BY IS '생성자 ID';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.PURCHASE_ORDER_ID IS '발주 ID';

CREATE TABLE RECEIPTS (
    RECEIPT_ID NUMBER NOT NULL,
    RECEIPT_MEMO VARCHAR2(1000),
    RECEIVED_AT DATE DEFAULT SYSDATE NOT NULL,
    PURCHASE_ORDER_ID NUMBER NOT NULL,
    CONSTRAINT PK_RECEIPTS PRIMARY KEY (RECEIPT_ID),
    CONSTRAINT FK_RECEIPTS_PUR_REQ FOREIGN KEY (PURCHASE_ORDER_ID)
        REFERENCES PURCHASE_ORDERS (PURCHASE_ORDER_ID)
);

CREATE SEQUENCE SEQ_RECEIPT START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE RECEIPTS IS '입고';
COMMENT ON COLUMN RECEIPTS.RECEIPT_ID IS '입고 ID';
COMMENT ON COLUMN RECEIPTS.RECEIPT_MEMO IS '입고 메모';
COMMENT ON COLUMN RECEIPTS.RECEIVED_AT IS '입고일시';
COMMENT ON COLUMN RECEIPTS.PURCHASE_ORDER_ID IS '발주 ID';

CREATE TABLE RECEIPT_ITEMS (
    RECEIPT_ITEM_ID NUMBER NOT NULL,
    RECEIVED_QUANTITY NUMBER(10) NOT NULL,
    DEFECT_QUANTITY NUMBER(10) DEFAULT 0 NOT NULL,
    RECEIPT_ITEM_MEMO VARCHAR2(1000),
    RECEIPT_ID NUMBER NOT NULL,
    PURCHASE_ORDER_ITEM_ID NUMBER NOT NULL,
    CONSTRAINT PK_RECEIPT_ITEMS PRIMARY KEY (RECEIPT_ITEM_ID),
    CONSTRAINT UK_RECEIPT_ITEM_PUR UNIQUE (RECEIPT_ID, PURCHASE_ORDER_ITEM_ID),
    CONSTRAINT FK_RECEIPT_ITEM_RECEIPT FOREIGN KEY (RECEIPT_ID)
        REFERENCES RECEIPTS (RECEIPT_ID),
    CONSTRAINT FK_RECEIPT_ITEM_PUR_ITEM FOREIGN KEY (PURCHASE_ORDER_ITEM_ID)
        REFERENCES PURCHASE_ORDER_ITEMS (PURCHASE_ORDER_ITEM_ID)
);

CREATE SEQUENCE SEQ_RECEIPT_ITEM START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE RECEIPT_ITEMS IS '입고 상세';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIPT_ITEM_ID IS '입고 상세 ID';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIVED_QUANTITY IS '실수령 수량';
COMMENT ON COLUMN RECEIPT_ITEMS.DEFECT_QUANTITY IS '불량 수량';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIPT_ITEM_MEMO IS '입고 상세 메모';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIPT_ID IS '입고 ID';
COMMENT ON COLUMN RECEIPT_ITEMS.PURCHASE_ORDER_ITEM_ID IS '발주 상세 ID';

CREATE TABLE STORE_CLOSINGS (
    STORE_CLOSING_ID NUMBER NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    CLOSING_MEMO VARCHAR2(1000),
    CLOSED_AT DATE DEFAULT SYSDATE NOT NULL,
    STORE_ID NUMBER NOT NULL,
    CONSTRAINT PK_STORE_CLS PRIMARY KEY (STORE_CLOSING_ID),
    CONSTRAINT UK_STORE_CLS_DATE UNIQUE (STORE_ID, BUSINESS_DATE),
    CONSTRAINT FK_STORE_CLS_STORE FOREIGN KEY (STORE_ID)
        REFERENCES STORES (STORE_ID)
);

CREATE SEQUENCE SEQ_STORE_CLS START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORE_CLOSINGS IS '점포 마감';
COMMENT ON COLUMN STORE_CLOSINGS.STORE_CLOSING_ID IS '점포 마감 ID';
COMMENT ON COLUMN STORE_CLOSINGS.BUSINESS_DATE IS '영업일';
COMMENT ON COLUMN STORE_CLOSINGS.CLOSING_MEMO IS '마감 메모';
COMMENT ON COLUMN STORE_CLOSINGS.CLOSED_AT IS '마감일시';
COMMENT ON COLUMN STORE_CLOSINGS.STORE_ID IS '점포 ID';

CREATE TABLE STORE_CLOSING_ITEMS (
    STORE_CLOSING_ITEM_ID NUMBER NOT NULL,
    SYSTEM_QUANTITY NUMBER(10) NOT NULL,
    PHYSICAL_QUANTITY NUMBER(10) NOT NULL,
    DISPOSAL_QUANTITY NUMBER(10) DEFAULT 0 NOT NULL,
    CLOSING_ITEM_MEMO VARCHAR2(1000),
    MATERIAL_NAME_SNAPSHOT VARCHAR2(100) NOT NULL,
    STORE_CLOSING_ID NUMBER NOT NULL,
    STORE_INVENTORY_ID NUMBER NOT NULL,
    CONSTRAINT PK_STORE_CLS_ITEM PRIMARY KEY (STORE_CLOSING_ITEM_ID),
    CONSTRAINT UK_STORE_CLS_ITEM_INV UNIQUE (STORE_CLOSING_ID, STORE_INVENTORY_ID),
    CONSTRAINT FK_STORE_CLS_ITEM_CLS FOREIGN KEY (STORE_CLOSING_ID)
        REFERENCES STORE_CLOSINGS (STORE_CLOSING_ID),
    CONSTRAINT FK_STORE_CLS_ITEM_INV FOREIGN KEY (STORE_INVENTORY_ID)
        REFERENCES STORE_INVENTORIES (STORE_INVENTORY_ID)
);

CREATE SEQUENCE SEQ_STORE_CLS_ITEM START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORE_CLOSING_ITEMS IS '점포 마감 상세';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.STORE_CLOSING_ITEM_ID IS '점포 마감 상세 ID';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.SYSTEM_QUANTITY IS '전산 재고 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.PHYSICAL_QUANTITY IS '실재고 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.DISPOSAL_QUANTITY IS '폐기 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.CLOSING_ITEM_MEMO IS '마감 상세 메모';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.MATERIAL_NAME_SNAPSHOT IS '자재명 스냅샷';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.STORE_CLOSING_ID IS '점포 마감 ID';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.STORE_INVENTORY_ID IS '점포 재고 ID';

CREATE TABLE INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID NUMBER NOT NULL,
    TRANSACTION_TYPE VARCHAR2(30) NOT NULL,
    REASON VARCHAR2(1000),
    TRANSACTION_MEMO VARCHAR2(1000),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY NUMBER NOT NULL,
    STORE_ID NUMBER NOT NULL,
    RECEIPT_ID NUMBER,
    STORE_CLOSING_ID NUMBER,
    CONSTRAINT PK_INV_TX PRIMARY KEY (INVENTORY_TRANSACTION_ID),
    CONSTRAINT CK_INV_TX_TRANSACTION_TYPE CHECK (TRANSACTION_TYPE IN ('RECEIPT', 'STORE_CLOSING', 'ADJUSTMENT')),
    CONSTRAINT FK_INV_TX_USER FOREIGN KEY (CREATED_BY)
        REFERENCES USERS (USER_NO),
    CONSTRAINT FK_INV_TX_STORE FOREIGN KEY (STORE_ID)
        REFERENCES STORES (STORE_ID),
    CONSTRAINT FK_INV_TX_RECEIPT FOREIGN KEY (RECEIPT_ID)
        REFERENCES RECEIPTS (RECEIPT_ID),
    CONSTRAINT FK_INV_TX_CLS FOREIGN KEY (STORE_CLOSING_ID)
        REFERENCES STORE_CLOSINGS (STORE_CLOSING_ID)
);

CREATE SEQUENCE SEQ_INV_TX START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INVENTORY_TRANSACTIONS IS '재고 변동 이력';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.INVENTORY_TRANSACTION_ID IS '재고 변동 이력 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.TRANSACTION_TYPE IS '변동 유형';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.REASON IS '사유';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.TRANSACTION_MEMO IS '재고 변동 메모';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.CREATED_AT IS '처리일시';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.CREATED_BY IS '처리자 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.STORE_ID IS '점포 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.RECEIPT_ID IS '입고 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.STORE_CLOSING_ID IS '점포 마감 ID';

CREATE TABLE INVENTORY_TRANSACTION_ITEMS (
    INVENTORY_TRANSACTION_ITEM_ID NUMBER NOT NULL,
    BEFORE_QUANTITY NUMBER(10) NOT NULL,
    AFTER_QUANTITY NUMBER(10) NOT NULL,
    INVENTORY_TRANSACTION_ID NUMBER NOT NULL,
    STORE_INVENTORY_ID NUMBER NOT NULL,
    CONSTRAINT PK_INV_TX_ITEM PRIMARY KEY (INVENTORY_TRANSACTION_ITEM_ID),
    CONSTRAINT UK_INV_TX_ITEM_MAT UNIQUE (INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID),
    CONSTRAINT FK_INV_TX_ITEM_TX FOREIGN KEY (INVENTORY_TRANSACTION_ID)
        REFERENCES INVENTORY_TRANSACTIONS (INVENTORY_TRANSACTION_ID),
    CONSTRAINT FK_INV_TX_ITEM_INV FOREIGN KEY (STORE_INVENTORY_ID)
        REFERENCES STORE_INVENTORIES (STORE_INVENTORY_ID)
);

CREATE SEQUENCE SEQ_INV_TX_ITEM START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INVENTORY_TRANSACTION_ITEMS IS '재고 변동 이력 상세';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.INVENTORY_TRANSACTION_ITEM_ID IS '재고 변동 이력 상세 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.BEFORE_QUANTITY IS '변동 전 수량';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.AFTER_QUANTITY IS '변동 후 수량';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.INVENTORY_TRANSACTION_ID IS '재고 변동 이력 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.STORE_INVENTORY_ID IS '점포 재고 ID';

CREATE TABLE NOTICES (
    NOTICE_ID NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    DELETED_AT DATE,
    CONSTRAINT PK_NOTICES PRIMARY KEY (NOTICE_ID)
);

CREATE SEQUENCE SEQ_NOTICE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE NOTICES IS '공지사항';
COMMENT ON COLUMN NOTICES.NOTICE_ID IS '공지사항 ID';
COMMENT ON COLUMN NOTICES.TITLE IS '제목';
COMMENT ON COLUMN NOTICES.CONTENT IS '내용';
COMMENT ON COLUMN NOTICES.CREATED_AT IS '생성일시';
COMMENT ON COLUMN NOTICES.DELETED_AT IS '삭제일시';

CREATE TABLE NOTICE_FILES (
    NOTICE_FILE_ID NUMBER NOT NULL,
    ORIGINAL_NAME VARCHAR2(255) NOT NULL,
    STORED_NAME VARCHAR2(255) NOT NULL,
    STORAGE_PATH VARCHAR2(500) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    DELETED_AT DATE,
    NOTICE_ID NUMBER NOT NULL,
    CONSTRAINT PK_NOTICE_FILES PRIMARY KEY (NOTICE_FILE_ID),
    CONSTRAINT FK_NOTICE_FILES_NOTICE FOREIGN KEY (NOTICE_ID)
        REFERENCES NOTICES (NOTICE_ID)
);

CREATE SEQUENCE SEQ_NOTICE_FILE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE NOTICE_FILES IS '공지사항 파일';
COMMENT ON COLUMN NOTICE_FILES.NOTICE_FILE_ID IS '공지사항 파일 ID';
COMMENT ON COLUMN NOTICE_FILES.ORIGINAL_NAME IS '원본 파일명';
COMMENT ON COLUMN NOTICE_FILES.STORED_NAME IS '저장 파일명';
COMMENT ON COLUMN NOTICE_FILES.STORAGE_PATH IS '저장 경로';
COMMENT ON COLUMN NOTICE_FILES.CREATED_AT IS '생성일시';
COMMENT ON COLUMN NOTICE_FILES.DELETED_AT IS '삭제일시';
COMMENT ON COLUMN NOTICE_FILES.NOTICE_ID IS '공지사항 ID';

CREATE TABLE INQUIRIES (
    INQUIRY_ID NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    ANSWER_CONTENT CLOB,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    ANSWERED_AT DATE,
    DELETED_AT DATE,
    STORE_ID NUMBER NOT NULL,
    CONSTRAINT PK_INQUIRIES PRIMARY KEY (INQUIRY_ID),
    CONSTRAINT FK_INQUIRIES_STORE FOREIGN KEY (STORE_ID)
        REFERENCES STORES (STORE_ID)
);

CREATE SEQUENCE SEQ_INQ START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INQUIRIES IS '문의사항';
COMMENT ON COLUMN INQUIRIES.INQUIRY_ID IS '문의사항 ID';
COMMENT ON COLUMN INQUIRIES.TITLE IS '제목';
COMMENT ON COLUMN INQUIRIES.CONTENT IS '내용';
COMMENT ON COLUMN INQUIRIES.ANSWER_CONTENT IS '답변 내용';
COMMENT ON COLUMN INQUIRIES.CREATED_AT IS '생성일시';
COMMENT ON COLUMN INQUIRIES.ANSWERED_AT IS '답변일시';
COMMENT ON COLUMN INQUIRIES.DELETED_AT IS '삭제일시';
COMMENT ON COLUMN INQUIRIES.STORE_ID IS '점포 ID';

CREATE TABLE INQUIRY_FILES (
    INQUIRY_FILE_ID NUMBER NOT NULL,
    ORIGINAL_NAME VARCHAR2(255) NOT NULL,
    STORED_NAME VARCHAR2(255) NOT NULL,
    STORAGE_PATH VARCHAR2(500) NOT NULL,
    ATTACH_TARGET CHAR(1) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    DELETED_AT DATE,
    INQUIRY_ID NUMBER NOT NULL,
    CONSTRAINT PK_INQUIRY_FILES PRIMARY KEY (INQUIRY_FILE_ID),
    CONSTRAINT CK_INQUIRY_FILES_ATTACH_TARGET CHECK (ATTACH_TARGET IN ('Q', 'A')),
    CONSTRAINT FK_INQUIRY_FILES_INQUIRY FOREIGN KEY (INQUIRY_ID)
        REFERENCES INQUIRIES (INQUIRY_ID)
);

CREATE SEQUENCE SEQ_INQ_FILE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INQUIRY_FILES IS '문의사항 파일';
COMMENT ON COLUMN INQUIRY_FILES.INQUIRY_FILE_ID IS '문의사항 파일 ID';
COMMENT ON COLUMN INQUIRY_FILES.ORIGINAL_NAME IS '원본 파일명';
COMMENT ON COLUMN INQUIRY_FILES.STORED_NAME IS '저장 파일명';
COMMENT ON COLUMN INQUIRY_FILES.STORAGE_PATH IS '저장 경로';
COMMENT ON COLUMN INQUIRY_FILES.CREATED_AT IS '생성일시';
COMMENT ON COLUMN INQUIRY_FILES.DELETED_AT IS '삭제일시';
COMMENT ON COLUMN INQUIRY_FILES.INQUIRY_ID IS '문의사항 ID';
