-- =========================================================
-- 30_seed_receipt.sql
-- 역할:
--   - RECEIVED 상태 발주에 대응하는 입고 시나리오 데이터 시딩
-- 포함 범위:
--   - RECEIPTS
--   - RECEIPT_ITEMS
--   - INVENTORY_TRANSACTIONS
--   - INVENTORY_TRANSACTION_ITEMS
--   - STORE_INVENTORIES 현재고 반영
-- =========================================================

INSERT INTO RECEIPTS (RECEIPT_ID, RECEIPT_MEMO, RECEIVED_AT, PURCHASE_ORDER_ID) VALUES
    (1, '정기 발주 입고 완료', SYSDATE - 3, 6);

INSERT INTO RECEIPT_ITEMS (RECEIPT_ITEM_ID, RECEIVED_QUANTITY, DEFECT_QUANTITY, RECEIPT_ITEM_MEMO, RECEIPT_ID, PURCHASE_ORDER_ITEM_ID) VALUES
    (1, 30, 0, '냉동 상태 양호', 1, 13);
INSERT INTO RECEIPT_ITEMS (RECEIPT_ITEM_ID, RECEIVED_QUANTITY, DEFECT_QUANTITY, RECEIPT_ITEM_MEMO, RECEIPT_ID, PURCHASE_ORDER_ITEM_ID) VALUES
    (2, 20, 0, '파손 없음', 1, 14);
INSERT INTO RECEIPT_ITEMS (RECEIPT_ITEM_ID, RECEIVED_QUANTITY, DEFECT_QUANTITY, RECEIPT_ITEM_MEMO, RECEIPT_ID, PURCHASE_ORDER_ITEM_ID) VALUES
    (3, 15, 0, '냉동 보관 완료', 1, 15);

INSERT INTO INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID,
    TRANSACTION_TYPE,
    REASON,
    TRANSACTION_MEMO,
    CREATED_AT,
    CREATED_BY,
    STORE_ID,
    RECEIPT_ID,
    STORE_CLOSING_ID
) VALUES (
    1,
    'RECEIPT',
    '발주 입고 반영',
    '발주 6번 입고에 따른 재고 증가',
    SYSDATE - 3,
    4,
    3,
    1,
    NULL
);

INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (1, 110, 140, 1, 30);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (2, 130, 150, 1, 31);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (3, 48, 63, 1, 39);

UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 140,
       UPDATED_AT = SYSDATE - 3
 WHERE STORE_INVENTORY_ID = 30;

UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 150,
       UPDATED_AT = SYSDATE - 3
 WHERE STORE_INVENTORY_ID = 31;

UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 63,
       UPDATED_AT = SYSDATE - 3
 WHERE STORE_INVENTORY_ID = 39;
