-- =========================================================
-- 40_seed_inventory_transaction.sql
-- 역할:
--   - 재고 변동 전용 추가 시나리오 데이터 시딩
-- 담당 범위:
--   - INVENTORY_TRANSACTIONS
--   - INVENTORY_TRANSACTION_ITEMS
--   - STORE_INVENTORIES 후속 반영
-- 작성 원칙:
--   - 입고 이후 수동 조정 이력을 별도 기록
--   - 현재고는 이 파일 실행 후 시연 최종 상태로 수렴
-- =========================================================

-- 5. 강남점 양상추 실사 조정
INSERT INTO INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID, TRANSACTION_TYPE, REASON, TRANSACTION_MEMO, CREATED_AT, CREATED_BY, STORE_ID, RECEIPT_ID, STORE_CLOSING_ID
) VALUES (
    5, 'ADJUSTMENT', '실사 재고 조정', '양상추 세척 손실분을 반영해 현재고를 조정함', TRUNC(DATE '2026-06-17') - 10 + (18 / 24), 2, 1, NULL, NULL
);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (13, 54, 50, 5, 4);
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 50,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 10 + (18 / 24)
 WHERE STORE_INVENTORY_ID = 4;

-- 6. 강남점 육류/채소 부족 상태 확정
INSERT INTO INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID, TRANSACTION_TYPE, REASON, TRANSACTION_MEMO, CREATED_AT, CREATED_BY, STORE_ID, RECEIPT_ID, STORE_CLOSING_ID
) VALUES (
    6, 'ADJUSTMENT', '영업 후 재고 보정', '누적 판매분을 반영해 비프패티와 토마토 현재고를 보정함', TRUNC(DATE '2026-06-17') - 2 + (19 / 24), 2, 1, NULL, NULL
);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (14, 33, 12, 6, 2);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (15, 14, 10, 6, 5);
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 12,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 2 + (19 / 24)
 WHERE STORE_INVENTORY_ID = 2;
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 10,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 2 + (19 / 24)
 WHERE STORE_INVENTORY_ID = 5;

-- 7. 강남점 소스류/베이컨 조정
INSERT INTO INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID, TRANSACTION_TYPE, REASON, TRANSACTION_MEMO, CREATED_AT, CREATED_BY, STORE_ID, RECEIPT_ID, STORE_CLOSING_ID
) VALUES (
    7, 'ADJUSTMENT', '폐기 및 집계 조정', '케첩 폐기와 베이컨 소진을 반영함', TRUNC(DATE '2026-06-17') - 1 + (21 / 24), 2, 1, NULL, NULL
);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (16, 34, 18, 7, 12);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (17, 6, 0, 7, 8);
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 18,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 1 + (21 / 24)
 WHERE STORE_INVENTORY_ID = 12;
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 0,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 1 + (21 / 24)
 WHERE STORE_INVENTORY_ID = 8;

-- 8. 동대문점 정상 운영 조정
INSERT INTO INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID, TRANSACTION_TYPE, REASON, TRANSACTION_MEMO, CREATED_AT, CREATED_BY, STORE_ID, RECEIPT_ID, STORE_CLOSING_ID
) VALUES (
    8, 'ADJUSTMENT', '실사 재고 반영', '양상추와 양파 실사 결과를 반영함', TRUNC(DATE '2026-06-17') - 2 + (17 / 24), 3, 2, NULL, NULL
);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (18, 16, 14, 8, 28);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (19, 34, 38, 8, 30);
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 14,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 2 + (17 / 24)
 WHERE STORE_INVENTORY_ID = 28;
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 38,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 2 + (17 / 24)
 WHERE STORE_INVENTORY_ID = 30;

-- 9. 종로점 부족 재고 심화
INSERT INTO INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID, TRANSACTION_TYPE, REASON, TRANSACTION_MEMO, CREATED_AT, CREATED_BY, STORE_ID, RECEIPT_ID, STORE_CLOSING_ID
) VALUES (
    9, 'ADJUSTMENT', '실사 재고 조정', '양상추와 베이컨 재고 차이를 반영함', TRUNC(DATE '2026-06-17') - 2 + (20 / 24), 4, 3, NULL, NULL
);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (20, 12, 8, 9, 52);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (21, 6, 0, 9, 56);
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 8,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 2 + (20 / 24)
 WHERE STORE_INVENTORY_ID = 52;
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 0,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 2 + (20 / 24)
 WHERE STORE_INVENTORY_ID = 56;

-- 10. 종로점 육류/감자 재고 차감
INSERT INTO INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID, TRANSACTION_TYPE, REASON, TRANSACTION_MEMO, CREATED_AT, CREATED_BY, STORE_ID, RECEIPT_ID, STORE_CLOSING_ID
) VALUES (
    10, 'ADJUSTMENT', '미반영 사용량 보정', '비프패티와 감자튀김의 누락 사용량을 반영함', TRUNC(DATE '2026-06-17') - 1 + (18 / 24), 4, 3, NULL, NULL
);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (22, 32, 12, 10, 50);
INSERT INTO INVENTORY_TRANSACTION_ITEMS (INVENTORY_TRANSACTION_ITEM_ID, BEFORE_QUANTITY, AFTER_QUANTITY, INVENTORY_TRANSACTION_ID, STORE_INVENTORY_ID) VALUES
    (23, 30, 10, 10, 59);
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 12,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 1 + (18 / 24)
 WHERE STORE_INVENTORY_ID = 50;
UPDATE STORE_INVENTORIES
   SET CURRENT_QUANTITY = 10,
       UPDATED_AT = TRUNC(DATE '2026-06-17') - 1 + (18 / 24)
 WHERE STORE_INVENTORY_ID = 59;
