-- 기존 테이블 삭제
DROP TABLE STORE CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE_NO;

-- 점장/점주 테이블
CREATE TABLE MANAGER (
    MANAGER_ID VARCHAR2(50) PRIMARY KEY,
    MANAGER_NAME VARCHAR2(100),
    MANAGER_PHONE VARCHAR2(20),
    MANAGER_EMAIL VARCHAR2(100)
);

-- 점포 테이블
CREATE TABLE STORE (
    STORE_CODE NUMBER PRIMARY KEY,
    STORE_NAME VARCHAR2(100),
    STORE_STATUS VARCHAR2(20),
    STORE_PHONE VARCHAR2(20),
    STORE_ADDRESS VARCHAR2(300),
    STORE_DETAIL_ADDRESS VARCHAR2(300),
    OPEN_DATE DATE,
    MANAGER_ID VARCHAR2(50),

    CONSTRAINT FK_STORE_MANAGER
    FOREIGN KEY (MANAGER_ID)
    REFERENCES MANAGER(MANAGER_ID)
);

-- 점포 코드 시퀀스
CREATE SEQUENCE SEQ_STORE_NO
START WITH 115
INCREMENT BY 1
NOCACHE;

-- 점장 데이터
INSERT INTO MANAGER VALUES (
    'manager01',
    '김점장',
    '010-9999-8888',
    'manager01@test.com'
);

-- 점포 더미 데이터
INSERT INTO STORE VALUES (
    110,
    '역삼B',
    '영업중',
    '010-1111-2222',
    '서울특별시 강남구 테헤란로14길 6',
    '남도빌딩',
    TO_DATE('2026-02-25', 'YYYY-MM-DD'),
    'manager01'
);

COMMIT;