-- GPT 작성 데이터 무결성 장담못함
-- 테스트용으로만 사용할 것
-- 더미데이터 초기화는 TableScript.sql 사용할 것
-- 260602

-- =====================================================
-- USERS (기존 2건 외 8건 추가)
-- =====================================================

INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'owner02','pw','김철수','010-1111-1111','[owner02@burgerstack.com](mailto:owner02@burgerstack.com)','OWNER','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'owner03','pw','이영희','010-2222-2222','[owner03@burgerstack.com](mailto:owner03@burgerstack.com)','OWNER','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'owner04','pw','박민수','010-3333-3333','[owner04@burgerstack.com](mailto:owner04@burgerstack.com)','OWNER','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'owner05','pw','최지훈','010-4444-4444','[owner05@burgerstack.com](mailto:owner05@burgerstack.com)','OWNER','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'owner06','pw','정수진','010-5555-5555','[owner06@burgerstack.com](mailto:owner06@burgerstack.com)','OWNER','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'owner07','pw','강민호','010-6666-6666','[owner07@burgerstack.com](mailto:owner07@burgerstack.com)','OWNER','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'owner08','pw','한지민','010-7777-7777','[owner08@burgerstack.com](mailto:owner08@burgerstack.com)','OWNER','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'owner09','pw','윤서준','010-8888-8888','[owner09@burgerstack.com](mailto:owner09@burgerstack.com)','OWNER','ACTIVE',1,SYSDATE,NULL,NULL);

-- =====================================================
-- STORES (10건)
-- OWNER_USER_ID = 2~10
-- =====================================================

INSERT INTO STORES VALUES (SEQ_STORE.NEXTVAL,'STORE001','강남점','02-1111-1111','서울 강남구',2,'OPEN',1,SYSDATE,NULL,NULL);
INSERT INTO STORES VALUES (SEQ_STORE.NEXTVAL,'STORE002','잠실점','02-1111-1112','서울 송파구',3,'OPEN',1,SYSDATE,NULL,NULL);
INSERT INTO STORES VALUES (SEQ_STORE.NEXTVAL,'STORE003','홍대점','02-1111-1113','서울 마포구',4,'OPEN',1,SYSDATE,NULL,NULL);
INSERT INTO STORES VALUES (SEQ_STORE.NEXTVAL,'STORE004','신촌점','02-1111-1114','서울 서대문구',5,'OPEN',1,SYSDATE,NULL,NULL);
INSERT INTO STORES VALUES (SEQ_STORE.NEXTVAL,'STORE005','건대점','02-1111-1115','서울 광진구',6,'OPEN',1,SYSDATE,NULL,NULL);
INSERT INTO STORES VALUES (SEQ_STORE.NEXTVAL,'STORE006','수원점','031-111-1111','경기 수원시',7,'OPEN',1,SYSDATE,NULL,NULL);
INSERT INTO STORES VALUES (SEQ_STORE.NEXTVAL,'STORE007','분당점','031-111-1112','경기 성남시',8,'OPEN',1,SYSDATE,NULL,NULL);
INSERT INTO STORES VALUES (SEQ_STORE.NEXTVAL,'STORE008','인천점','032-111-1111','인천 남동구',9,'OPEN',1,SYSDATE,NULL,NULL);
INSERT INTO STORES VALUES (SEQ_STORE.NEXTVAL,'STORE009','대전점','042-111-1111','대전 서구',10,'OPEN',1,SYSDATE,NULL,NULL);

-- =====================================================
-- FILES (10건)
-- =====================================================

INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'bun.jpg','bun_1.jpg','/upload/materials','image/jpeg',12000,NULL,1,SYSDATE);
INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'patty.jpg','patty_1.jpg','/upload/materials','image/jpeg',15000,NULL,1,SYSDATE);
INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'cheese.jpg','cheese_1.jpg','/upload/materials','image/jpeg',11000,NULL,1,SYSDATE);
INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'lettuce.jpg','lettuce_1.jpg','/upload/materials','image/jpeg',9000,NULL,1,SYSDATE);
INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'tomato.jpg','tomato_1.jpg','/upload/materials','image/jpeg',9500,NULL,1,SYSDATE);
INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'onion.jpg','onion_1.jpg','/upload/materials','image/jpeg',9200,NULL,1,SYSDATE);
INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'pickle.jpg','pickle_1.jpg','/upload/materials','image/jpeg',8800,NULL,1,SYSDATE);
INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'bacon.jpg','bacon_1.jpg','/upload/materials','image/jpeg',10200,NULL,1,SYSDATE);
INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'egg.jpg','egg_1.jpg','/upload/materials','image/jpeg',10400,NULL,1,SYSDATE);
INSERT INTO FILES VALUES (SEQ_FILE.NEXTVAL,'sauce.jpg','sauce_1.jpg','/upload/materials','image/jpeg',9700,NULL,1,SYSDATE);

-- =====================================================
-- MATERIALS (10건)
-- =====================================================

INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT001','참깨번','BUN',500,1000,1,'참깨 번','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT002','비프패티','PATTY',2000,3500,2,'소고기 패티','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT003','체다치즈','CHEESE',300,700,3,'체다 치즈','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT004','양상추','VEGETABLE',200,500,4,'양상추','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT005','토마토','VEGETABLE',250,600,5,'토마토','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT006','양파','VEGETABLE',150,400,6,'양파','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT007','피클','VEGETABLE',100,300,7,'피클','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT008','베이컨','TOPPING',800,1500,8,'베이컨','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT009','계란후라이','TOPPING',500,1000,9,'계란','ACTIVE',1,SYSDATE,NULL,NULL);
INSERT INTO MATERIALS VALUES (SEQ_MATERIAL.NEXTVAL,'MAT010','마요네즈','SAUCE',100,300,10,'마요네즈','ACTIVE',1,SYSDATE,NULL,NULL);

-- =====================================================
-- STORE_INVENTORIES (10건)
-- =====================================================

INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,1,1,100,20,1,SYSDATE,NULL,NULL);
INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,1,2,80,20,1,SYSDATE,NULL,NULL);
INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,1,3,120,30,1,SYSDATE,NULL,NULL);
INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,1,4,150,30,1,SYSDATE,NULL,NULL);
INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,1,5,90,20,1,SYSDATE,NULL,NULL);
INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,2,1,100,20,1,SYSDATE,NULL,NULL);
INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,2,2,80,20,1,SYSDATE,NULL,NULL);
INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,2,3,120,30,1,SYSDATE,NULL,NULL);
INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,2,4,150,30,1,SYSDATE,NULL,NULL);
INSERT INTO STORE_INVENTORIES VALUES (SEQ_STORE_INV.NEXTVAL,2,5,90,20,1,SYSDATE,NULL,NULL);

-- =====================================================
-- PURCHASE_REQUESTS (10건)
-- =====================================================

INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 1, 'REQUESTED', 15000, '1번점 발주1', 2, SYSDATE, NULL, NULL);
INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 2, 'APPROVED', 20000, '2번점 발주', 3, SYSDATE, NULL, NULL);
INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 3, 'REQUESTED', 18000, '홍대점 발주', 4, SYSDATE, NULL, NULL);
INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 4, 'REJECTED', 12000, '신촌점 발주', 5, SYSDATE, NULL, NULL);
INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 5, 'APPROVED', 22000, '건대점 발주', 6, SYSDATE, NULL, NULL);
INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 6, 'REQUESTED', 30000, '수원점 발주', 7, SYSDATE, NULL, NULL);
INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 7, 'APPROVED', 27000, '분당점 발주', 8, SYSDATE, NULL, NULL);
INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 8, 'REQUESTED', 25000, '인천점 발주', 9, SYSDATE, NULL, NULL);
INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 9, 'APPROVED', 19000, '대전점 발주', 10, SYSDATE, NULL, NULL);
INSERT INTO PURCHASE_REQUESTS VALUES (SEQ_PUR_REQ.NEXTVAL, 1, 'REQUESTED', 21000, '강남점 추가발주', 2, SYSDATE, NULL, NULL);

-- =====================================================
-- PURCHASE_REQUEST_ITEMS (10건)
-- =====================================================

INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 1, 1, '참깨번', 500, 20, 0, 'REQUESTED', NULL, 10000);
INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 1, 2, '비프패티', 2000, 3, 0, 'REQUESTED', NULL, 6000);
INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 2, 3, '체다치즈', 300, 10, 10, 'APPROVED', NULL, 3000);
INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 2, 4, '양상추', 200, 15, 15, 'APPROVED', NULL, 3000);
INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 3, 5, '토마토', 250, 10, 0, 'REQUESTED', NULL, 2500);
INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 3, 6, '양파', 150, 10, 0, 'REQUESTED', NULL, 1500);
INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 4, 7, '피클', 100, 10, 0, 'REJECTED', '재고 충분', 1000);
INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 5, 8, '베이컨', 800, 5, 5, 'APPROVED', NULL, 4000);
INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 6, 9, '계란후라이', 500, 10, 0, 'REQUESTED', NULL, 5000);
INSERT INTO PURCHASE_REQUEST_ITEMS VALUES (SEQ_PUR_REQ_ITEM.NEXTVAL, 7, 10, '마요네즈', 100, 20, 20, 'APPROVED', NULL, 2000);

-- =====================================================
-- PURCHASE_REQUEST_HISTORIES (10건)
-- =====================================================

INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 1, NULL, 'REQUESTED', '생성', 2, SYSDATE);
INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 2, 'REQUESTED', 'APPROVED', '승인', 1, SYSDATE);
INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 3, NULL, 'REQUESTED', NULL, 4, SYSDATE);
INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 4, 'REQUESTED', 'REJECTED', '재고 충분', 1, SYSDATE);
INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 5, 'REQUESTED', 'APPROVED', NULL, 1, SYSDATE);
INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 6, NULL, 'REQUESTED', NULL, 7, SYSDATE);
INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 7, 'REQUESTED', 'APPROVED', NULL, 1, SYSDATE);
INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 8, NULL, 'REQUESTED', NULL, 9, SYSDATE);
INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 9, 'REQUESTED', 'APPROVED', NULL, 1, SYSDATE);
INSERT INTO PURCHASE_REQUEST_HISTORIES VALUES (SEQ_PUR_REQ_HIST.NEXTVAL, 10, NULL, 'REQUESTED', NULL, 2, SYSDATE);

-- =====================================================
-- RECEIPTS (10건)
-- =====================================================

INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 1, 1, '입고완료', 1, SYSDATE);
INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 2, 2, '정상입고', 1, SYSDATE);
INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 3, 3, '입고', 1, SYSDATE);
INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 4, 4, '부분입고', 1, SYSDATE);
INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 5, 5, '입고', 1, SYSDATE);
INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 6, 6, '입고', 1, SYSDATE);
INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 7, 7, '입고', 1, SYSDATE);
INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 8, 8, '입고', 1, SYSDATE);
INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 9, 9, '입고', 1, SYSDATE);
INSERT INTO RECEIPTS VALUES (SEQ_RECEIPT.NEXTVAL, 10, 1, '입고', 1, SYSDATE);

-- =====================================================
-- RECEIPT_ITEMS (10건)
-- =====================================================

INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 1, 1, 1, 20, 20, 0, '정상');
INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 2, 2, 2, 3, 3, 0, '정상');
INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 3, 3, 3, 10, 10, 0, NULL);
INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 4, 4, 4, 15, 14, 1, '파손');
INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 5, 5, 5, 10, 10, 0, NULL);
INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 6, 6, 6, 10, 10, 0, NULL);
INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 7, 7, 7, 10, 10, 0, NULL);
INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 8, 8, 8, 5, 5, 0, NULL);
INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 9, 9, 9, 10, 10, 0, NULL);
INSERT INTO RECEIPT_ITEMS VALUES (SEQ_RECEIPT_ITEM.NEXTVAL, 10, 10, 10, 20, 20, 0, NULL);

-- =====================================================
-- STORE_CLOSINGS (10건)
-- =====================================================

INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 1, SYSDATE, '정상마감', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 2, SYSDATE, '재고확인', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 3, SYSDATE, '정산', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 4, SYSDATE, '정상', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 5, SYSDATE, '마감', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 6, SYSDATE, '마감', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 7, SYSDATE, '정산', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 8, SYSDATE, '정상', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 9, SYSDATE, '마감', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 1, SYSDATE, '추가마감', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 1, SYSDATE, '정상마감', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 2, SYSDATE, '재고확인', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 3, SYSDATE, '정산', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 4, SYSDATE, '정상', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 5, SYSDATE, '마감', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 6, SYSDATE, '마감', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 7, SYSDATE, '정산', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 8, SYSDATE, '정상', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 9, SYSDATE, '마감', 1, SYSDATE);
INSERT INTO STORE_CLOSINGS VALUES (SEQ_STORE_CLS.NEXTVAL, 1, SYSDATE, '추가마감', 1, SYSDATE);

-- =====================================================
-- STORE_CLOSING_ITEMS (10건)
-- =====================================================

INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 1, 1, 100, 98, 2, 0, NULL);
INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 2, 2, 80, 80, 0, 0, NULL);
INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 3, 3, 120, 119, 1, 0, NULL);
INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 4, 4, 150, 150, 0, 0, NULL);
INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 5, 5, 90, 88, 2, 0, NULL);
INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 6, 6, 100, 100, 0, 0, NULL);
INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 7, 7, 70, 70, 0, 0, NULL);
INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 8, 8, 60, 60, 0, 0, NULL);
INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 9, 9, 50, 49, 1, 0, NULL);
INSERT INTO STORE_CLOSING_ITEMS VALUES (SEQ_STORE_CLS_ITEM.NEXTVAL, 10, 1, 100, 100, 0, 0, NULL);

-- =====================================================
-- INVENTORY_TRANSACTIONS (10건)
-- =====================================================

INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 1, 'RECEIPT', 1, '입고 반영', 1, SYSDATE);
INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 2, 'RECEIPT', 2, '입고', 1, SYSDATE);
INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 3, 'STORE_CLOSING', 3, '마감 반영', 1, SYSDATE);
INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 4, 'ADJUSTMENT', 4, '조정', 1, SYSDATE);
INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 5, 'RECEIPT', 5, '입고', 1, SYSDATE);
INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 6, 'STORE_CLOSING', 6, '마감', 1, SYSDATE);
INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 7, 'RECEIPT', 7, '입고', 1, SYSDATE);
INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 8, 'ADJUSTMENT', 8, '조정', 1, SYSDATE);
INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 9, 'RECEIPT', 9, '입고', 1, SYSDATE);
INSERT INTO INVENTORY_TRANSACTIONS VALUES (SEQ_INV_TX.NEXTVAL, 10, 'STORE_CLOSING', 10, '마감', 1, SYSDATE);

-- =====================================================
-- INVENTORY_TRANSACTION_ITEMS (10건)
-- =====================================================

INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 1, 1, 100, -20, 80);
INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 2, 2, 80, -10, 70);
INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 3, 3, 70, -5, 65);
INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 4, 4, 150, -10, 140);
INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 5, 5, 90, -20, 70);
INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 6, 6, 60, -5, 55);
INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 7, 7, 80, -10, 70);
INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 8, 8, 70, -10, 60);
INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 9, 9, 90, -20, 70);
INSERT INTO INVENTORY_TRANSACTION_ITEMS VALUES (SEQ_INV_TX_ITEM.NEXTVAL, 10, 10, 100, -30, 70);

-- =====================================================
-- NOTICES (10건)
-- =====================================================

INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지1','내용1',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지2','내용2',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지3','내용3',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지4','내용4',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지5','내용5',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지6','내용6',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지7','내용7',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지8','내용8',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지9','내용9',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지10','내용10',NULL,1,SYSDATE,NULL,NULL);

-- =====================================================
-- INQUIRIES (10건)
-- =====================================================

INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,1,'문의1','내용', 'WAITING', NULL, NULL, NULL, NULL, 2, SYSDATE, NULL, NULL);
INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,2,'문의2','내용', 'WAITING', NULL, NULL, NULL, NULL, 3, SYSDATE, NULL, NULL);
INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,3,'문의3','내용', 'ANSWERED', '답변', 1, SYSDATE, NULL, 4, SYSDATE, NULL, NULL);
INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,4,'문의4','내용', 'WAITING', NULL, NULL, NULL, NULL, 5, SYSDATE, NULL, NULL);
INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,5,'문의5','내용', 'WAITING', NULL, NULL, NULL, NULL, 6, SYSDATE, NULL, NULL);
INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,6,'문의6','내용', 'ANSWERED', '답변', 1, SYSDATE, NULL, 7, SYSDATE, NULL, NULL);
INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,7,'문의7','내용', 'WAITING', NULL, NULL, NULL, NULL, 8, SYSDATE, NULL, NULL);
INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,8,'문의8','내용', 'WAITING', NULL, NULL, NULL, NULL, 9, SYSDATE, NULL, NULL);
INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,9,'문의9','내용', 'WAITING', NULL, NULL, NULL, NULL, 10, SYSDATE, NULL, NULL);
INSERT INTO INQUIRIES VALUES (SEQ_INQ.NEXTVAL,10,'문의10','내용', 'WAITING', NULL, NULL, NULL, NULL, 2, SYSDATE, NULL, NULL);

COMMIT;
