/* =========================================================
   TableScript
   작성자: 송경민

   목차
   1. DROP
   2. 기준 / 공통
      - 사용자
      - 점포
      - 자재
      - 자재 파일
      - 점포 재고
   3. 발주
      - 발주
      - 발주 상세
      - 발주 이력
   4. 입고
      - 입고
      - 입고 상세
   5. 점포 마감
      - 점포 마감
      - 점포 마감 상세
   6. 재고 변동 이력
      - 재고 변동 이력
      - 재고 변동 이력 상세
   7. 공지사항
      - 공지사항
      - 공지사항 파일
   8. 문의사항
      - 문의사항
      - 문의사항 파일
   9. 데이터 시딩
      - 관리자 계정
      - 점주 계정 1, 2, 3
      - 점포 1, 2, 3
   ========================================================= */


-- =========================================================
-- 1. DROP
-- =========================================================


-- 문의사항
DROP TABLE INQUIRY_FILES CASCADE CONSTRAINTS;
DROP TABLE INQUIRIES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INQ_FILE;
DROP SEQUENCE SEQ_INQ;

-- 공지사항
DROP TABLE NOTICE_FILES CASCADE CONSTRAINTS;
DROP TABLE NOTICES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_NOTICE_FILE;
DROP SEQUENCE SEQ_NOTICE;

-- 재고 변동 이력
DROP TABLE INVENTORY_TRANSACTION_ITEMS CASCADE CONSTRAINTS;
DROP TABLE INVENTORY_TRANSACTIONS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INV_TX_ITEM;
DROP SEQUENCE SEQ_INV_TX;

-- 점포 마감
DROP TABLE STORE_CLOSING_ITEMS CASCADE CONSTRAINTS;
DROP TABLE STORE_CLOSINGS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE_CLS_ITEM;
DROP SEQUENCE SEQ_STORE_CLS;

-- 입고
DROP TABLE RECEIPT_ITEMS CASCADE CONSTRAINTS;
DROP TABLE RECEIPTS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_RECEIPT_ITEM;
DROP SEQUENCE SEQ_RECEIPT;

-- 발주
DROP TABLE PURCHASE_REQUEST_HISTORIES CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_REQUEST_ITEMS CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_REQUESTS CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_ORDER_HISTORIES CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_ORDER_ITEMS CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_ORDERS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PUR_REQ_HIST;
DROP SEQUENCE SEQ_PUR_REQ_ITEM;
DROP SEQUENCE SEQ_PUR_REQ;

-- 점포 재고
DROP TABLE STORE_INVENTORIES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE_INV;

-- 자재
DROP TABLE MATERIALS CASCADE CONSTRAINTS;
DROP TABLE MATERIAL_FILES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MATERIAL;
DROP SEQUENCE SEQ_MAT_FILE;

-- 점포
DROP TABLE STORES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE;

-- 사용자
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_USER;

-- (구) 파일
DROP TABLE FILES;
DROP SEQUENCE SEQ_FILE;
-- =========================================================
-- 2. 기준 / 공통
-- =========================================================

-- 사용자
CREATE TABLE USERS (
    USER_NO    NUMBER NOT NULL
    , USER_ID    VARCHAR2(50) NOT NULL
    , PASSWORD   VARCHAR2(255) NOT NULL
    , USER_NAME  VARCHAR2(50) NOT NULL
    , PHONE      VARCHAR2(30)
    , EMAIL      VARCHAR2(100)
    , ROLE       VARCHAR2(20) DEFAULT 'OWNER' NOT NULL
    , STATUS     VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
    , CREATED_AT DATE DEFAULT SYSDATE NOT NULL
    , CONSTRAINT PK_USERS PRIMARY KEY ( USER_NO )
    , CONSTRAINT UK_USERS_USER_ID UNIQUE ( USER_ID )
    , CONSTRAINT CK_USERS_ROLE CHECK ( ROLE IN ( 'OWNER', 'ADMIN' ) )
    , CONSTRAINT CK_USERS_STATUS CHECK ( STATUS IN ( 'ACTIVE', 'INACTIVE' ) )
);

CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE USERS IS
    '사용자';
COMMENT ON COLUMN USERS.USER_NO IS
    '사용자 번호';
COMMENT ON COLUMN USERS.USER_ID IS
    '아이디';
COMMENT ON COLUMN USERS.PASSWORD IS
    '비밀번호';
COMMENT ON COLUMN USERS.USER_NAME IS
    '이름';
COMMENT ON COLUMN USERS.PHONE IS
    '연락처';
COMMENT ON COLUMN USERS.EMAIL IS
    '이메일';
COMMENT ON COLUMN USERS.ROLE IS
    '역할';
COMMENT ON COLUMN USERS.STATUS IS
    '상태';
COMMENT ON COLUMN USERS.CREATED_AT IS
    '생성일시';

-- 점포
CREATE TABLE STORES (
    STORE_ID      NUMBER NOT NULL
    , STORE_CODE    VARCHAR2(30) NOT NULL
    , STORE_NAME    VARCHAR2(100) NOT NULL
    , PHONE         VARCHAR2(30)
    , ADDRESS       VARCHAR2(255) NOT NULL
    , STATUS        VARCHAR2(20) DEFAULT 'OPEN' NOT NULL
    , OWNER_USER_NO NUMBER NOT NULL
    , CREATED_AT    DATE DEFAULT SYSDATE NOT NULL
    , CONSTRAINT PK_STORES PRIMARY KEY ( STORE_ID )
    , CONSTRAINT UK_STORES_CODE UNIQUE ( STORE_CODE )
    , CONSTRAINT UK_STORES_OWNER UNIQUE ( OWNER_USER_NO )
    , CONSTRAINT CK_STORES_STATUS CHECK ( STATUS IN ( 'OPEN', 'CLOSED' ) )
    , CONSTRAINT FK_STORES_OWNER FOREIGN KEY ( OWNER_USER_NO )
        REFERENCES USERS ( USER_NO )
);

CREATE SEQUENCE SEQ_STORE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORES IS
    '점포';
COMMENT ON COLUMN STORES.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN STORES.STORE_CODE IS
    '점포 코드';
COMMENT ON COLUMN STORES.STORE_NAME IS
    '점포명';
COMMENT ON COLUMN STORES.PHONE IS
    '점포 전화번호';
COMMENT ON COLUMN STORES.ADDRESS IS
    '점포 주소';
COMMENT ON COLUMN STORES.STATUS IS
    '상태';
COMMENT ON COLUMN STORES.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN STORES.OWNER_USER_NO IS
    '점주 사용자 ID';



-- 자재
CREATE TABLE MATERIALS (
    MATERIAL_ID   NUMBER NOT NULL
    , MATERIAL_CODE VARCHAR2(30) NOT NULL
    , MATERIAL_NAME VARCHAR2(100) NOT NULL
    , MATERIAL_TYPE VARCHAR2(50) NOT NULL
    , SUPPLY_PRICE  NUMBER(12) NOT NULL
    , DETAILS       VARCHAR2(3000)
    , STATUS        VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
    , CREATED_AT    DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_AT    DATE
    , CONSTRAINT PK_MATERIALS PRIMARY KEY ( MATERIAL_ID )
    , CONSTRAINT UK_MATERIALS_CODE UNIQUE ( MATERIAL_CODE )
    , CONSTRAINT CK_MATERIALS_TYPE
        CHECK ( MATERIAL_TYPE IN ( 'AF', 'RF', 'FF', 'PK', 'KW', 'ET' ) )
    , CONSTRAINT CK_MATERIALS_STATUS CHECK ( STATUS IN ( 'ACTIVE', 'INACTIVE' ) )
);

-- 자재 유형
-- 'AF' 상온식품
-- 'RF' 냉장식품
-- 'FF' 냉동식품
-- 'PK' 포장재
-- 'KW' 주방용품
-- 'ET' 기타

CREATE SEQUENCE SEQ_MATERIAL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE MATERIALS IS
    '자재';
COMMENT ON COLUMN MATERIALS.MATERIAL_ID IS
    '자재 ID';
COMMENT ON COLUMN MATERIALS.MATERIAL_CODE IS
    '자재 코드';
COMMENT ON COLUMN MATERIALS.MATERIAL_NAME IS
    '자재명';
COMMENT ON COLUMN MATERIALS.MATERIAL_TYPE IS
    '자재 유형';
COMMENT ON COLUMN MATERIALS.SUPPLY_PRICE IS
    '공급가';
COMMENT ON COLUMN MATERIALS.STATUS IS
    '상태';
COMMENT ON COLUMN MATERIALS.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN MATERIALS.UPDATED_AT IS
    '수정일시';


-- 자재 파일
CREATE TABLE MATERIAL_FILES (
    MATERIAL_FILE_ID NUMBER NOT NULL
    , ORIGINAL_NAME    VARCHAR2(255) NOT NULL
    , STORED_NAME      VARCHAR2(255) NOT NULL
    , STORAGE_PATH     VARCHAR2(500) NOT NULL
    , CREATED_AT       DATE DEFAULT SYSDATE NOT NULL
    , DELETED_AT       DATE
    , MATERIAL_ID      NUMBER NOT NULL
    , CONSTRAINT PK_MATERIAL_FILES PRIMARY KEY ( MATERIAL_FILE_ID )
    , CONSTRAINT FK_MATERIAL_FILES_MAT FOREIGN KEY ( MATERIAL_ID )
        REFERENCES MATERIALS ( MATERIAL_ID )
);

CREATE SEQUENCE SEQ_MAT_FILE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE MATERIAL_FILES IS
    '자재 파일';
COMMENT ON COLUMN MATERIAL_FILES.MATERIAL_FILE_ID IS
    '자재 파일 ID';
COMMENT ON COLUMN MATERIAL_FILES.ORIGINAL_NAME IS
    '원본 파일명';
COMMENT ON COLUMN MATERIAL_FILES.STORED_NAME IS
    '저장 파일명';
COMMENT ON COLUMN MATERIAL_FILES.STORAGE_PATH IS
    '저장 경로';
COMMENT ON COLUMN MATERIAL_FILES.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN MATERIAL_FILES.DELETED_AT IS
    '삭제일시';
COMMENT ON COLUMN MATERIAL_FILES.MATERIAL_ID IS
    '자재 ID';


-- 점포 재고
CREATE TABLE STORE_INVENTORIES (
    STORE_INVENTORY_ID NUMBER NOT NULL
    , CURRENT_QUANTITY   NUMBER(10) DEFAULT 0 NOT NULL
    , SAFETY_QUANTITY    NUMBER(10) DEFAULT 0 NOT NULL
    , CREATED_AT         DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_AT         DATE
    , STORE_ID           NUMBER NOT NULL
    , MATERIAL_ID        NUMBER NOT NULL
    , CONSTRAINT PK_STORE_INV PRIMARY KEY ( STORE_INVENTORY_ID )
    , CONSTRAINT UK_STORE_INV_MAT UNIQUE ( STORE_ID
    , MATERIAL_ID )
    , CONSTRAINT FK_STORE_INV_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
    , CONSTRAINT FK_STORE_INV_MAT FOREIGN KEY ( MATERIAL_ID )
        REFERENCES MATERIALS ( MATERIAL_ID )
);

CREATE SEQUENCE SEQ_STORE_INV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORE_INVENTORIES IS
    '점포 재고';
COMMENT ON COLUMN STORE_INVENTORIES.STORE_INVENTORY_ID IS
    '점포 재고 ID';
COMMENT ON COLUMN STORE_INVENTORIES.CURRENT_QUANTITY IS
    '현재 재고 수량';
COMMENT ON COLUMN STORE_INVENTORIES.SAFETY_QUANTITY IS
    '안전 재고 수량';
COMMENT ON COLUMN STORE_INVENTORIES.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN STORE_INVENTORIES.UPDATED_AT IS
    '수정일시';
COMMENT ON COLUMN STORE_INVENTORIES.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN STORE_INVENTORIES.MATERIAL_ID IS
    '자재 ID';


-- =========================================================
-- 3. 발주
-- =========================================================

-- 발주
CREATE TABLE PURCHASE_ORDERS (
    PURCHASE_ORDER_ID NUMBER NOT NULL
    , TOTAL_AMOUNT      NUMBER(12) DEFAULT 0 NOT NULL
    , ORDER_MEMO        VARCHAR2(1000)
    , STATUS            VARCHAR2(30) DEFAULT 'REQUESTED' NOT NULL
    , CREATED_AT        DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_AT        DATE
    , STORE_ID          NUMBER NOT NULL
    , CONSTRAINT PK_PUR_REQ PRIMARY KEY ( PURCHASE_ORDER_ID )
    , CONSTRAINT CK_PUR_REQ_STATUS
        CHECK ( STATUS IN ( 'REQUESTED', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', 'CANCELED', 'RECEIVED' ) )
    , CONSTRAINT FK_PUR_REQ_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
);

CREATE SEQUENCE SEQ_PUR_REQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE PURCHASE_ORDERS IS
    '발주';
COMMENT ON COLUMN PURCHASE_ORDERS.PURCHASE_ORDER_ID IS
    '발주 ID';
COMMENT ON COLUMN PURCHASE_ORDERS.TOTAL_AMOUNT IS
    '총액';
COMMENT ON COLUMN PURCHASE_ORDERS.ORDER_MEMO IS
    '발주 메모';
COMMENT ON COLUMN PURCHASE_ORDERS.STATUS IS
    '상태';
COMMENT ON COLUMN PURCHASE_ORDERS.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN PURCHASE_ORDERS.UPDATED_AT IS
    '수정일시';
COMMENT ON COLUMN PURCHASE_ORDERS.STORE_ID IS
    '점포 ID';


-- 발주 상세
CREATE TABLE PURCHASE_ORDER_ITEMS (
    PURCHASE_ORDER_ITEM_ID NUMBER NOT NULL
    , REQUEST_QUANTITY       NUMBER(10) NOT NULL
    , APPROVED_QUANTITY      NUMBER(10) DEFAULT 0 NOT NULL
    , REJECT_REASON          VARCHAR2(1000)
    , MATERIAL_NAME_SNAPSHOT VARCHAR2(100) NOT NULL
    , SUPPLY_PRICE_SNAPSHOT  NUMBER(12) NOT NULL
    , MATERIAL_ID            NUMBER NOT NULL
    , PURCHASE_ORDER_ID      NUMBER NOT NULL
    , CONSTRAINT PK_PUR_REQ_ITEM PRIMARY KEY ( PURCHASE_ORDER_ITEM_ID )
    , CONSTRAINT UK_PUR_REQ_ITEM_MAT UNIQUE ( PURCHASE_ORDER_ID
    , MATERIAL_ID )
    , CONSTRAINT FK_PUR_ITEM_REQ FOREIGN KEY ( PURCHASE_ORDER_ID )
        REFERENCES PURCHASE_ORDERS ( PURCHASE_ORDER_ID )
    , CONSTRAINT FK_PUR_ITEM_MAT FOREIGN KEY ( MATERIAL_ID )
        REFERENCES MATERIALS ( MATERIAL_ID )
);

CREATE SEQUENCE SEQ_PUR_REQ_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE PURCHASE_ORDER_ITEMS IS
    '발주 상세';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.PURCHASE_ORDER_ITEM_ID IS
    '발주 상세 ID';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.REQUEST_QUANTITY IS
    '요청 수량';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.APPROVED_QUANTITY IS
    '승인 수량';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.REJECT_REASON IS
    '품목 반려 사유';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.MATERIAL_NAME_SNAPSHOT IS
    '자재명 스냅샷';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.SUPPLY_PRICE_SNAPSHOT IS
    '공급가 스냅샷';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.PURCHASE_ORDER_ID IS
    '발주 ID';
COMMENT ON COLUMN PURCHASE_ORDER_ITEMS.MATERIAL_ID IS
    '자재 ID';


-- 발주 이력
CREATE TABLE PURCHASE_ORDER_HISTORIES (
    PURCHASE_ORDER_HISTORY_ID NUMBER NOT NULL
    , TO_STATUS                 VARCHAR2(30) NOT NULL
    , REASON                    VARCHAR2(1000)
    , CREATED_AT                DATE DEFAULT SYSDATE NOT NULL
    , CREATED_BY                NUMBER NOT NULL
    , PURCHASE_ORDER_ID         NUMBER NOT NULL
    , CONSTRAINT PK_PUR_REQ_HIST PRIMARY KEY ( PURCHASE_ORDER_HISTORY_ID )
    , CONSTRAINT FK_PUR_HIST_REQ FOREIGN KEY ( PURCHASE_ORDER_ID )
        REFERENCES PURCHASE_ORDERS ( PURCHASE_ORDER_ID )
    , CONSTRAINT FK_PUR_HIST_USER FOREIGN KEY ( CREATED_BY )
        REFERENCES USERS ( USER_NO )
);

CREATE SEQUENCE SEQ_PUR_REQ_HIST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE PURCHASE_ORDER_HISTORIES IS
    '발주 이력';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.TO_STATUS IS
    '변경 후 상태';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.REASON IS
    '상태 변경 사유';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.CREATED_BY IS
    '생성자 ID';
COMMENT ON COLUMN PURCHASE_ORDER_HISTORIES.PURCHASE_ORDER_ID IS
    '발주 ID';


-- =========================================================
-- 4. 입고
-- =========================================================

-- 입고
CREATE TABLE RECEIPTS (
    RECEIPT_ID        NUMBER NOT NULL
    , RECEIPT_MEMO      VARCHAR2(1000)
    , RECEIVED_AT       DATE DEFAULT SYSDATE NOT NULL
    , PURCHASE_ORDER_ID NUMBER NOT NULL
    , CONSTRAINT PK_RECEIPTS PRIMARY KEY ( RECEIPT_ID )
    , CONSTRAINT FK_RECEIPTS_PUR_REQ FOREIGN KEY ( PURCHASE_ORDER_ID )
        REFERENCES PURCHASE_ORDERS ( PURCHASE_ORDER_ID )
);

CREATE SEQUENCE SEQ_RECEIPT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE RECEIPTS IS
    '입고';
COMMENT ON COLUMN RECEIPTS.RECEIPT_ID IS
    '입고 ID';
COMMENT ON COLUMN RECEIPTS.RECEIPT_MEMO IS
    '입고 메모';
COMMENT ON COLUMN RECEIPTS.RECEIVED_AT IS
    '입고일시';
COMMENT ON COLUMN RECEIPTS.PURCHASE_ORDER_ID IS
    '발주 ID';


-- 입고 상세
CREATE TABLE RECEIPT_ITEMS (
    RECEIPT_ITEM_ID        NUMBER NOT NULL
    , RECEIVED_QUANTITY      NUMBER(10) NOT NULL
    , DEFECT_QUANTITY        NUMBER(10) DEFAULT 0 NOT NULL
    , RECEIPT_ITEM_MEMO      VARCHAR2(1000)
    , RECEIPT_ID             NUMBER NOT NULL
    , PURCHASE_ORDER_ITEM_ID NUMBER NOT NULL
    , CONSTRAINT PK_RECEIPT_ITEMS PRIMARY KEY ( RECEIPT_ITEM_ID )
    , CONSTRAINT UK_RECEIPT_ITEM_PUR UNIQUE ( RECEIPT_ID
    , PURCHASE_ORDER_ITEM_ID )
    , CONSTRAINT FK_RECEIPT_ITEM_RECEIPT FOREIGN KEY ( RECEIPT_ID )
        REFERENCES RECEIPTS ( RECEIPT_ID )
    , CONSTRAINT FK_RECEIPT_ITEM_PUR_ITEM FOREIGN KEY ( PURCHASE_ORDER_ITEM_ID )
        REFERENCES PURCHASE_ORDER_ITEMS ( PURCHASE_ORDER_ITEM_ID )
);

CREATE SEQUENCE SEQ_RECEIPT_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE RECEIPT_ITEMS IS
    '입고 상세';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIPT_ITEM_ID IS
    '입고 상세 ID';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIVED_QUANTITY IS
    '실수령 수량';
COMMENT ON COLUMN RECEIPT_ITEMS.DEFECT_QUANTITY IS
    '불량 수량';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIPT_ITEM_MEMO IS
    '입고 상세 메모';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIPT_ID IS
    '입고 ID';
COMMENT ON COLUMN RECEIPT_ITEMS.PURCHASE_ORDER_ITEM_ID IS
    '발주 상세 ID';


-- =========================================================
-- 5. 점포 마감
-- =========================================================

-- 점포 마감
CREATE TABLE STORE_CLOSINGS (
    STORE_CLOSING_ID NUMBER NOT NULL
    , BUSINESS_DATE    DATE NOT NULL
    , CLOSING_MEMO     VARCHAR2(1000)
    , CLOSED_AT        DATE DEFAULT SYSDATE NOT NULL
    , STORE_ID         NUMBER NOT NULL
    , CONSTRAINT PK_STORE_CLS PRIMARY KEY ( STORE_CLOSING_ID )
    , CONSTRAINT UK_STORE_CLS_DATE UNIQUE ( STORE_ID
    , BUSINESS_DATE )
    , CONSTRAINT FK_STORE_CLS_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
);

CREATE SEQUENCE SEQ_STORE_CLS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORE_CLOSINGS IS
    '점포 마감';
COMMENT ON COLUMN STORE_CLOSINGS.STORE_CLOSING_ID IS
    '점포 마감 ID';
COMMENT ON COLUMN STORE_CLOSINGS.BUSINESS_DATE IS
    '영업일';
COMMENT ON COLUMN STORE_CLOSINGS.CLOSING_MEMO IS
    '마감 메모';
COMMENT ON COLUMN STORE_CLOSINGS.CLOSED_AT IS
    '마감일시';
COMMENT ON COLUMN STORE_CLOSINGS.STORE_ID IS
    '점포 ID';


-- 점포 마감 상세
CREATE TABLE STORE_CLOSING_ITEMS (
    STORE_CLOSING_ITEM_ID  NUMBER NOT NULL
    , SYSTEM_QUANTITY        NUMBER(10) NOT NULL
    , PHYSICAL_QUANTITY      NUMBER(10) NOT NULL
    , DISPOSAL_QUANTITY      NUMBER(10) DEFAULT 0 NOT NULL
    , CLOSING_ITEM_MEMO      VARCHAR2(1000)
    , MATERIAL_NAME_SNAPSHOT VARCHAR2(100) NOT NULL
    , STORE_CLOSING_ID       NUMBER NOT NULL
    , STORE_INVENTORY_ID     NUMBER NOT NULL
    , CONSTRAINT PK_STORE_CLS_ITEM PRIMARY KEY ( STORE_CLOSING_ITEM_ID )
    , CONSTRAINT UK_STORE_CLS_ITEM_INV UNIQUE ( STORE_CLOSING_ID
    , STORE_INVENTORY_ID )
    , CONSTRAINT FK_STORE_CLS_ITEM_CLS FOREIGN KEY ( STORE_CLOSING_ID )
        REFERENCES STORE_CLOSINGS ( STORE_CLOSING_ID )
    , CONSTRAINT FK_STORE_CLS_ITEM_INV FOREIGN KEY ( STORE_INVENTORY_ID )
        REFERENCES STORE_INVENTORIES ( STORE_INVENTORY_ID )
);

CREATE SEQUENCE SEQ_STORE_CLS_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORE_CLOSING_ITEMS IS
    '점포 마감 상세';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.STORE_CLOSING_ITEM_ID IS
    '점포 마감 상세 ID';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.SYSTEM_QUANTITY IS
    '전산 재고 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.PHYSICAL_QUANTITY IS
    '실재고 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.DISPOSAL_QUANTITY IS
    '폐기 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.CLOSING_ITEM_MEMO IS
    '마감 상세 메모';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.MATERIAL_NAME_SNAPSHOT IS
    '자재명 스냅샷';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.STORE_CLOSING_ID IS
    '점포 마감 ID';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.STORE_INVENTORY_ID IS
    '점포 재고 ID';


-- =========================================================
-- 6. 재고 변동 이력
-- =========================================================

-- 재고 변동 이력
CREATE TABLE INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID NUMBER NOT NULL
    , TRANSACTION_TYPE         VARCHAR2(30) NOT NULL
    , REASON                   VARCHAR2(1000)
    , TRANSACTION_MEMO         VARCHAR2(1000)
    , CREATED_AT               DATE DEFAULT SYSDATE NOT NULL
    , CREATED_BY               NUMBER NOT NULL
    , STORE_ID                 NUMBER NOT NULL
    , RECEIPT_ID               NUMBER
    , STORE_CLOSING_ID         NUMBER
    , CONSTRAINT PK_INV_TX PRIMARY KEY ( INVENTORY_TRANSACTION_ID )
    , CONSTRAINT CK_INV_TX_TRANSACTION_TYPE
        CHECK ( TRANSACTION_TYPE IN ( 'RECEIPT', 'STORE_CLOSING', 'ADJUSTMENT' ) )
    , CONSTRAINT FK_INV_TX_USER FOREIGN KEY ( CREATED_BY )
        REFERENCES USERS ( USER_NO )
    , CONSTRAINT FK_INV_TX_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
    , CONSTRAINT FK_INV_TX_RECEIPT FOREIGN KEY ( RECEIPT_ID )
        REFERENCES RECEIPTS ( RECEIPT_ID )
    , CONSTRAINT FK_INV_TX_CLS FOREIGN KEY ( STORE_CLOSING_ID )
        REFERENCES STORE_CLOSINGS ( STORE_CLOSING_ID )
);

CREATE SEQUENCE SEQ_INV_TX START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INVENTORY_TRANSACTIONS IS
    '재고 변동 이력';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.INVENTORY_TRANSACTION_ID IS
    '재고 변동 이력 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.TRANSACTION_TYPE IS
    '변동 유형';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.REASON IS
    '사유';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.TRANSACTION_MEMO IS
    '재고 변동 메모';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.CREATED_AT IS
    '처리일시';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.CREATED_BY IS
    '처리자 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.RECEIPT_ID IS
    '입고 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.STORE_CLOSING_ID IS
    '점포 마감 ID';


-- 재고 변동 이력 상세
CREATE TABLE INVENTORY_TRANSACTION_ITEMS (
    INVENTORY_TRANSACTION_ITEM_ID NUMBER NOT NULL
    , BEFORE_QUANTITY               NUMBER(10) NOT NULL
    , AFTER_QUANTITY                NUMBER(10) NOT NULL
    , INVENTORY_TRANSACTION_ID      NUMBER NOT NULL
    , STORE_INVENTORY_ID            NUMBER NOT NULL
    , CONSTRAINT PK_INV_TX_ITEM PRIMARY KEY ( INVENTORY_TRANSACTION_ITEM_ID )
    , CONSTRAINT UK_INV_TX_ITEM_MAT UNIQUE ( INVENTORY_TRANSACTION_ID
    , STORE_INVENTORY_ID )
    , CONSTRAINT FK_INV_TX_ITEM_TX FOREIGN KEY ( INVENTORY_TRANSACTION_ID )
        REFERENCES INVENTORY_TRANSACTIONS ( INVENTORY_TRANSACTION_ID )
    , CONSTRAINT FK_INV_TX_ITEM_INV FOREIGN KEY ( STORE_INVENTORY_ID )
        REFERENCES STORE_INVENTORIES ( STORE_INVENTORY_ID )
);

CREATE SEQUENCE SEQ_INV_TX_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INVENTORY_TRANSACTION_ITEMS IS
    '재고 변동 이력 상세';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.INVENTORY_TRANSACTION_ITEM_ID IS
    '재고 변동 이력 상세 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.BEFORE_QUANTITY IS
    '변동 전 수량';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.AFTER_QUANTITY IS
    '변동 후 수량';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.INVENTORY_TRANSACTION_ID IS
    '재고 변동 이력 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.STORE_INVENTORY_ID IS
    '점포 재고 ID';


-- =========================================================
-- 7. 공지사항
-- =========================================================

-- 공지사항
CREATE TABLE NOTICES (
    NOTICE_ID  NUMBER NOT NULL
    , TITLE      VARCHAR2(200) NOT NULL
    , CONTENT    CLOB NOT NULL
    , CREATED_AT DATE DEFAULT SYSDATE NOT NULL
    , DELETED_AT DATE
    , CONSTRAINT PK_NOTICES PRIMARY KEY ( NOTICE_ID )
);

CREATE SEQUENCE SEQ_NOTICE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE NOTICES IS
    '공지사항';
COMMENT ON COLUMN NOTICES.NOTICE_ID IS
    '공지사항 ID';
COMMENT ON COLUMN NOTICES.TITLE IS
    '제목';
COMMENT ON COLUMN NOTICES.CONTENT IS
    '내용';
COMMENT ON COLUMN NOTICES.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN NOTICES.DELETED_AT IS
    '삭제일시';



-- 공지사항 파일
CREATE TABLE NOTICE_FILES (
    NOTICE_FILE_ID NUMBER NOT NULL
    , ORIGINAL_NAME  VARCHAR2(255) NOT NULL
    , STORED_NAME    VARCHAR2(255) NOT NULL
    , STORAGE_PATH   VARCHAR2(500) NOT NULL
    , CREATED_AT     DATE DEFAULT SYSDATE NOT NULL
    , DELETED_AT     DATE
    , NOTICE_ID      NUMBER NOT NULL
    , CONSTRAINT PK_NOTICE_FILES PRIMARY KEY ( NOTICE_FILE_ID )
    , CONSTRAINT FK_NOTICE_FILES_NOTICE FOREIGN KEY ( NOTICE_ID )
        REFERENCES NOTICES ( NOTICE_ID )
);

CREATE SEQUENCE SEQ_NOTICE_FILE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE NOTICE_FILES IS
    '공지사항 파일';
COMMENT ON COLUMN NOTICE_FILES.NOTICE_FILE_ID IS
    '공지사항 파일 ID';
COMMENT ON COLUMN NOTICE_FILES.ORIGINAL_NAME IS
    '원본 파일명';
COMMENT ON COLUMN NOTICE_FILES.STORED_NAME IS
    '저장 파일명';
COMMENT ON COLUMN NOTICE_FILES.STORAGE_PATH IS
    '저장 경로';
COMMENT ON COLUMN NOTICE_FILES.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN NOTICE_FILES.DELETED_AT IS
    '삭제일시';
COMMENT ON COLUMN NOTICE_FILES.NOTICE_ID IS
    '공지사항 ID';


-- =========================================================
-- 8. 문의사항
-- =========================================================

-- 문의사항
CREATE TABLE INQUIRIES (
    INQUIRY_ID     NUMBER NOT NULL
    , TITLE          VARCHAR2(200) NOT NULL
    , CONTENT        CLOB NOT NULL
    , ANSWER_CONTENT CLOB
    , CREATED_AT     DATE DEFAULT SYSDATE NOT NULL
    , ANSWERED_AT    DATE
    , DELETED_AT     DATE
    , STORE_ID       NUMBER NOT NULL
    , CONSTRAINT PK_INQUIRIES PRIMARY KEY ( INQUIRY_ID )
    , CONSTRAINT FK_INQUIRIES_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
);

CREATE SEQUENCE SEQ_INQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INQUIRIES IS
    '문의사항';
COMMENT ON COLUMN INQUIRIES.INQUIRY_ID IS
    '문의사항 ID';
COMMENT ON COLUMN INQUIRIES.TITLE IS
    '제목';
COMMENT ON COLUMN INQUIRIES.CONTENT IS
    '내용';
COMMENT ON COLUMN INQUIRIES.ANSWER_CONTENT IS
    '답변 내용';
COMMENT ON COLUMN INQUIRIES.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN INQUIRIES.ANSWERED_AT IS
    '답변일시';
COMMENT ON COLUMN INQUIRIES.DELETED_AT IS
    '삭제일시';
COMMENT ON COLUMN INQUIRIES.STORE_ID IS
    '점포 ID';


-- 문의사항 파일
CREATE TABLE INQUIRY_FILES (
    INQUIRY_FILE_ID NUMBER NOT NULL
    , ORIGINAL_NAME   VARCHAR2(255) NOT NULL
    , STORED_NAME     VARCHAR2(255) NOT NULL
    , STORAGE_PATH    VARCHAR2(500) NOT NULL
    , ATTACH_TARGET   CHAR(1) NOT NULL
    , CREATED_AT      DATE DEFAULT SYSDATE NOT NULL
    , DELETED_AT      DATE
    , INQUIRY_ID      NUMBER NOT NULL
    , CONSTRAINT PK_INQUIRY_FILES PRIMARY KEY ( INQUIRY_FILE_ID )
    , CONSTRAINT CK_INQUIRY_FILES_ATTACH_TARGET CHECK ( ATTACH_TARGET IN ( 'Q', 'A' ) )
    , CONSTRAINT FK_INQUIRY_FILES_INQUIRY FOREIGN KEY ( INQUIRY_ID )
        REFERENCES INQUIRIES ( INQUIRY_ID )
);

CREATE SEQUENCE SEQ_INQ_FILE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INQUIRY_FILES IS
    '문의사항 파일';
COMMENT ON COLUMN INQUIRY_FILES.INQUIRY_FILE_ID IS
    '문의사항 파일 ID';
COMMENT ON COLUMN INQUIRY_FILES.ORIGINAL_NAME IS
    '원본 파일명';
COMMENT ON COLUMN INQUIRY_FILES.STORED_NAME IS
    '저장 파일명';
COMMENT ON COLUMN INQUIRY_FILES.STORAGE_PATH IS
    '저장 경로';
COMMENT ON COLUMN INQUIRY_FILES.CREATED_AT IS
    '생성일시';
COMMENT ON COLUMN INQUIRY_FILES.DELETED_AT IS
    '삭제일시';
COMMENT ON COLUMN INQUIRY_FILES.INQUIRY_ID IS
    '문의사항 ID';



-- =========================================================
-- 9. 데이터 시딩
-- =========================================================

-- 관리자 계정
INSERT INTO USERS (
    USER_NO
    , USER_ID
    , PASSWORD
    , USER_NAME
    , PHONE
    , EMAIL
    , ROLE
) VALUES ( SEQ_USER.NEXTVAL
         , 'admin'
         , '$2a$10$A/GEtn8aVhdFaHXV1wTeeefiNg7Y5j08J6Ry1g59lGlAekUOXoBFq' -- adminpass
         , '관리자'
         , '010-0000-0000'
         , 'admin@burgerstack.com'
         , 'ADMIN' );

-- 점주 계정 1
INSERT INTO USERS (
    USER_NO
    , USER_ID
    , PASSWORD
    , USER_NAME
    , PHONE
    , EMAIL
) VALUES ( SEQ_USER.NEXTVAL
         , 'owner01'
         , '$2a$10$lDCgUXLq5qKbDY0NIs/JvuwH6flkRDSL0Hjwjw0Jo/lfDWd0FBSOO' -- pass01
         , '홍길동'
         , '010-8635-3654'
         , 'gd.hong@burgerstack.com' );

-- 점포 1
INSERT INTO STORES (
    STORE_ID
    , STORE_CODE
    , STORE_NAME
    , PHONE
    , ADDRESS
    , OWNER_USER_NO
) VALUES ( SEQ_STORE.NEXTVAL
         , 'DUMMY_STORE_01'
         , '버거스택 강남점'
         , '010-9620-8465'
         , '서울특별시 강남구'
         , 2 );

-- 점주 계정 2
INSERT INTO USERS (
    USER_NO
    , USER_ID
    , PASSWORD
    , USER_NAME
    , PHONE
    , EMAIL
) VALUES ( SEQ_USER.NEXTVAL
         , 'owner02'
         , '$2a$10$lDCgUXLq5qKbDY0NIs/JvuwH6flkRDSL0Hjwjw0Jo/lfDWd0FBSOO' -- pass01
         , '박길동'
         , '010-4659-5678'
         , 'gdpack@burgerstack.com' );

-- 점포 2
INSERT INTO STORES (
    STORE_ID
    , STORE_CODE
    , STORE_NAME
    , PHONE
    , ADDRESS
    , OWNER_USER_NO
) VALUES ( SEQ_STORE.NEXTVAL
         , 'DUMMY_STORE_02'
         , '버거스택 동대문점'
         , '010-7635-2854'
         , '서울특별시 동대문구'
         , 3 );

-- 점주 계정 3
INSERT INTO USERS (
    USER_NO
    , USER_ID
    , PASSWORD
    , USER_NAME
    , PHONE
    , EMAIL
) VALUES ( SEQ_USER.NEXTVAL
         , 'owner03'
         , '$2a$10$lDCgUXLq5qKbDY0NIs/JvuwH6flkRDSL0Hjwjw0Jo/lfDWd0FBSOO' -- pass01
         , '송길동'
         , '010-3580-3965'
         , 'song_gd@burgerstack.com' );

-- 점포 3
INSERT INTO STORES (
    STORE_ID
    , STORE_CODE
    , STORE_NAME
    , PHONE
    , ADDRESS
    , OWNER_USER_NO
) VALUES ( SEQ_STORE.NEXTVAL
         , 'DUMMY_STORE_03'
         , '버거스택 종로점'
         , '010-2367-6457'
         , '서울특별시 종로구'
         , 4 );


-- 자재 더미 데이터
INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-001'
         , '참깨번'
         , 'INGREDIENT'
         , 1000 );

INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-002'
         , '비프패티'
         , 'INGREDIENT'
         , 2000 );

INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-003'
         , '체다치즈'
         , 'INGREDIENT'
         , 300 );

INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-004'
         , '양상추'
         , 'INGREDIENT'
         , 200 );

INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-005'
         , '토마토'
         , 'INGREDIENT'
         , 250 );

INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-006'
         , '양파'
         , 'INGREDIENT'
         , 150 );

INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-007'
         , '피클'
         , 'INGREDIENT'
         , 100 );

INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-008'
         , '베이컨'
         , 'INGREDIENT'
         , 800 );

INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-009'
         , '계란'
         , 'INGREDIENT'
         , 500 );

INSERT INTO MATERIALS (
    MATERIAL_ID
    , MATERIAL_CODE
    , MATERIAL_NAME
    , MATERIAL_TYPE
    , SUPPLY_PRICE
) VALUES ( SEQ_MATERIAL.NEXTVAL
         , 'DM-010'
         , '마요네즈'
         , 'INGREDIENT'
         , 100 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 120
         , 30
         , 1
         , 1 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 80
         , 20
         , 1
         , 2 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 100
         , 25
         , 1
         , 3 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 60
         , 20
         , 1
         , 4 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 55
         , 20
         , 1
         , 5 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 70
         , 20
         , 1
         , 6 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 90
         , 25
         , 1
         , 7 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 40
         , 15
         , 1
         , 8 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 50
         , 15
         , 1
         , 9 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 110
         , 30
         , 1
         , 10 );


INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 95
         , 30
         , 2
         , 1 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 45
         , 20
         , 2
         , 2 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 70
         , 25
         , 2
         , 3 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 35
         , 20
         , 2
         , 4 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 30
         , 20
         , 2
         , 5 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 42
         , 20
         , 2
         , 6 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 65
         , 25
         , 2
         , 7 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 18
         , 15
         , 2
         , 8 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 22
         , 15
         , 2
         , 9 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 75
         , 30
         , 2
         , 10 );


INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 150
         , 30
         , 3
         , 1 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 110
         , 20
         , 3
         , 2 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 130
         , 25
         , 3
         , 3 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 85
         , 20
         , 3
         , 4 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 78
         , 20
         , 3
         , 5 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 95
         , 20
         , 3
         , 6 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 105
         , 25
         , 3
         , 7 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 70
         , 15
         , 3
         , 8 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 65
         , 15
         , 3
         , 9 );

INSERT INTO STORE_INVENTORIES (
    STORE_INVENTORY_ID
    , CURRENT_QUANTITY
    , SAFETY_QUANTITY
    , STORE_ID
    , MATERIAL_ID
) VALUES ( SEQ_STORE_INV.NEXTVAL
         , 140
         , 30
         , 3
         , 10 );


-- 커밋
COMMIT;
