-- 공지사항 더미
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다1', '내용입니다1');
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다2', '내용입니다2');
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다3', '내용입니다3');
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다4', '내용입니다4');
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다5', '내용입니다5');
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다6', '내용입니다6');
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다7', '내용입니다7');
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다8', '내용입니다8');
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다9', '내용입니다9');
INSERT INTO NOTICES (NOTICE_ID, TITLE, CONTENT) 
VALUES (SEQ_NOTICE.NEXTVAL, '제목입니다10', '내용입니다10');

COMMIT;

-- 공지사항 게시글수 조회
SELECT COUNT(*)
  FROM NOTICES
 WHERE DELETED_AT IS NULL;

-- 공지사항 전체 목록 조회
SELECT NOTICE_ID  AS noticeId
     , TITLE      AS title
     , CREATED_AT AS createdAt
  FROM NOTICES
 WHERE DELETED_AT IS NULL
 ORDER BY CREATED_AT DESC;
 
 
-- 공지사항 상세 조회
-- 1. 제목/내용
SELECT NOTICE_ID AS noticeId
     , TITLE AS title
     , CONTENT AS content
     , CREATED_AT createdAt
  FROM NOTICES
 WHERE DELETED_AT IS NULL
   AND NOTICE_ID = ?;
   
-- 2. 첨부파일
SELECT NOTICE_FILE_ID AS noticdFileId
     , ORIGINAL_NAME AS originalName
     , STORED_NAME AS storedName
     , STORAGE_PATH AS storagePath
     , NOTICE_ID AS noticeId
  FROM NOTICE_FILES
 WHERE DELETED_AT IS NULL
   AND NOTICE_ID = ?;



-- 공지사항 수정
-- 추후 파일 조인 구문 추가
UPDATE NOTICES
   SET TITLE = ?
     , CONTENT = ?
     , UPDATED_AT = ?
 WHERE DELETED_AT IS NULL
   AND NOTICE_ID = ?;
   
-- 공지사항 삭제
UPDATE NOTICES
   SET DELETED_AT = SYSDATE
 WHERE DELETED_AT IS NULL
   AND NOTICE_ID = ?;
   
   
